//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Contexto de la aplicación RIA.
    /// </summary>
    /// <remarks>
    /// Este contexto extiende la base para poner los servicios de la aplicación y los tipos a disposición
    /// del código y el xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Definiciones de método de extensibilidad

        /// <summary>
        /// Este método se invoca desde el constructor una vez completada la inicialización y
        /// se puede utilizar para configurar más objetos.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Inicializa una nueva instancia de la clase WebContext.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Obtiene el contexto registrado como un objeto de vigencia con la aplicación actual.
        /// </summary>
        /// Si no hay ninguna aplicación actual, se produce una <exception cref="InvalidOperationException">;
        /// también si no se ha agregado contexto o si se ha agregado más de un contexto.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
