#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_IMPORT")]
	public partial class Linq_BD_IMPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public Linq_BD_IMPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_IMPORTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_BD_IMPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_BD_IMPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_BD_IMPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_BD_IMPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IMPORT_MOVISTAR> IMPORT_MOVISTAR
		{
			get
			{
				return this.GetTable<IMPORT_MOVISTAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IMPORT_MOVISTAR")]
	public partial class IMPORT_MOVISTAR
	{
		
		private string _NOMBRE;
		
		private System.Nullable<int> _RUT;
		
		private string _DV;
		
		private string _CORREO;
		
		private System.Nullable<int> _CLAVE;
		
		public IMPORT_MOVISTAR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUT", DbType="Int")]
		public System.Nullable<int> RUT
		{
			get
			{
				return this._RUT;
			}
			set
			{
				if ((this._RUT != value))
				{
					this._RUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", DbType="VarChar(1)")]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this._DV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(100)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE", DbType="Int")]
		public System.Nullable<int> CLAVE
		{
			get
			{
				return this._CLAVE;
			}
			set
			{
				if ((this._CLAVE != value))
				{
					this._CLAVE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
