#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_FOL_FOLCOURIER")]
	public partial class Linq_SPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public Linq_SPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_FOL_FOLCOURIERConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_SPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_SPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_SPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq_SPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_FOL_INFORME_TRANSPORTE")]
		public ISingleResult<PR_FOL_INFORME_TRANSPORTEResult> PR_FOL_INFORME_TRANSPORTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INI", DbType="VarChar(30)")] string fECHA_INI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_FIN", DbType="VarChar(30)")] string fECHA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_SUC", DbType="Int")] System.Nullable<int> iD_SUC)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fECHA_INI, fECHA_FIN, iD_SUC);
			return ((ISingleResult<PR_FOL_INFORME_TRANSPORTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_FOL_GRA_OTS_GRAL_DIA")]
		public ISingleResult<PR_FOL_GRA_OTS_GRAL_DIAResult> PR_FOL_GRA_OTS_GRAL_DIA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PR_FOL_GRA_OTS_GRAL_DIAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_FOL_GRA_OTS_GRAL_DIA_DETALLE")]
		public ISingleResult<PR_FOL_GRA_OTS_GRAL_DIA_DETALLEResult> PR_FOL_GRA_OTS_GRAL_DIA_DETALLE()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PR_FOL_GRA_OTS_GRAL_DIA_DETALLEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_FOL_GRA_OTS_GRAL_SERVICIO")]
		public ISingleResult<PR_FOL_GRA_OTS_GRAL_SERVICIOResult> PR_FOL_GRA_OTS_GRAL_SERVICIO()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<PR_FOL_GRA_OTS_GRAL_SERVICIOResult>)(result.ReturnValue));
		}
	}
	
	public partial class PR_FOL_INFORME_TRANSPORTEResult
	{
		
		private string _OT;

        private string _MANIFIESTO;
		
		private string _FL_FOL_OTD_REFERENCIA1;
		
		private System.Nullable<int> _FL_FOL_CANT_DOCTO;
		
		private string _FL_FOL_OTP_FECHA_CREACION;
		
		private string _FL_FOL_OTD_FECHA_ESTIMADA;
		
		private string _FECHA_ENTREGA_REAL;
		
		private string _FL_SUCURSAL_ESTADO;
		
		private string _FL_FOL_EST_NOMBRE;
		
		private string _FECHA_ESTADO;
		
		private System.Nullable<int> _FL_FOL_OTD_BULTO;
		
		private System.Nullable<float> _FL_FOL_OTD_PESO;
		
		private System.Nullable<float> _PESO_VOLUMETRICO;
		
		private System.Nullable<int> _FL_PAR_SER_FACTOR_VOLUMETRICO;
		
		private System.Nullable<float> _PESO_FACTURADO;
		
		private string _FL_PAR_SUC_NOMBRE_ORG;
		
		private string _FL_PAR_SUC_NOMBRE;
		
		private string _FL_CLI_EMP_FANTASIA;
		
		private string _FL_PAR_SER_NOMBRE;
		
		private string _FL_FOL_OTD_DESTINATARIO_NOMBRE;
		
		private string _FL_FOL_OTD_DESTINATARIO_RUT;
		
		private string _FL_FOL_OTD_DESTINATARIO_DIRECCION;
		
		private string _FL_FOL_OTD_DESTINATARIO_NUMERO;
		
		private string _FL_PAR_COM_NOMBRE;
		
		private string _FL_PAR_COM_CODIGO;
		
		private string _FL_FOL_OTD_TELEFONO;
		
		private string _FL_PAR_CON_NOMBRE_T;
		
		private string _FL_PAR_TRA_MODELO_T;
		
		private string _FL_PAR_TRA_PATENTE_T;
		
		private string _FL_PAR_CON_NOMBRE_S;
		
		private string _FL_PAR_TRA_MODELO_S;
		
		private string _FL_PAR_TRA_PATENTE_S;
		
		private string _FL_FOL_ENT_RECIBE;
		
		private string _FL_FOL_ENT_RUT;
		
		private string _FL_FOL_OTD_REFERENCIA2;
		
		private string _TIPO_DES_DEV;
		
		private string _FL_FOL_EDO_NOMBRE;
		
		private string _FL_FOL_RDO_FECHA;
		
		private string _Fe_Gd_Estimada;
		
		private string _FL_FOL_PRIMERA_VISITA;
		
		private string _FL_PAR_VIA_NOMBRE;
		
		private decimal _OTPadre;
		
		private System.Nullable<decimal> _FL_FOL_DOA_CONTRAPAGO;
		
		private string _FL_FOL_TOB_NOMBRE;
		
		private string _FECHA_ULTIMO_ESTADO;
		
		private string _OBS_ULTIMO_ESTADO;
		
		private string _FL_FOL_OCA_OBSERVACION;
		
		public PR_FOL_INFORME_TRANSPORTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OT", DbType="VarChar(61)")]
		public string OT
		{
			get
			{
				return this._OT;
			}
			set
			{
				if ((this._OT != value))
				{
					this._OT = value;
				}
			}
		}

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MANIFIESTO", DbType = "VarChar(12)")]
        public string MANIFIESTO
        {
            get
            {
                return this._MANIFIESTO;
            }
            set
            {
                if ((this._MANIFIESTO != value))
                {
                    this._MANIFIESTO = value;
                }
            }
        }
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_REFERENCIA1", DbType="VarChar(100)")]
		public string FL_FOL_OTD_REFERENCIA1
		{
			get
			{
				return this._FL_FOL_OTD_REFERENCIA1;
			}
			set
			{
				if ((this._FL_FOL_OTD_REFERENCIA1 != value))
				{
					this._FL_FOL_OTD_REFERENCIA1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_CANT_DOCTO", DbType="Int")]
		public System.Nullable<int> FL_FOL_CANT_DOCTO
		{
			get
			{
				return this._FL_FOL_CANT_DOCTO;
			}
			set
			{
				if ((this._FL_FOL_CANT_DOCTO != value))
				{
					this._FL_FOL_CANT_DOCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTP_FECHA_CREACION", DbType="VarChar(10)")]
		public string FL_FOL_OTP_FECHA_CREACION
		{
			get
			{
				return this._FL_FOL_OTP_FECHA_CREACION;
			}
			set
			{
				if ((this._FL_FOL_OTP_FECHA_CREACION != value))
				{
					this._FL_FOL_OTP_FECHA_CREACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_FECHA_ESTIMADA", DbType="VarChar(10)")]
		public string FL_FOL_OTD_FECHA_ESTIMADA
		{
			get
			{
				return this._FL_FOL_OTD_FECHA_ESTIMADA;
			}
			set
			{
				if ((this._FL_FOL_OTD_FECHA_ESTIMADA != value))
				{
					this._FL_FOL_OTD_FECHA_ESTIMADA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ENTREGA_REAL", DbType="VarChar(61)")]
		public string FECHA_ENTREGA_REAL
		{
			get
			{
				return this._FECHA_ENTREGA_REAL;
			}
			set
			{
				if ((this._FECHA_ENTREGA_REAL != value))
				{
					this._FECHA_ENTREGA_REAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_SUCURSAL_ESTADO", DbType="VarChar(200)")]
		public string FL_SUCURSAL_ESTADO
		{
			get
			{
				return this._FL_SUCURSAL_ESTADO;
			}
			set
			{
				if ((this._FL_SUCURSAL_ESTADO != value))
				{
					this._FL_SUCURSAL_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_EST_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FL_FOL_EST_NOMBRE
		{
			get
			{
				return this._FL_FOL_EST_NOMBRE;
			}
			set
			{
				if ((this._FL_FOL_EST_NOMBRE != value))
				{
					this._FL_FOL_EST_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ESTADO", DbType="VarChar(10)")]
		public string FECHA_ESTADO
		{
			get
			{
				return this._FECHA_ESTADO;
			}
			set
			{
				if ((this._FECHA_ESTADO != value))
				{
					this._FECHA_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_BULTO", DbType="Int")]
		public System.Nullable<int> FL_FOL_OTD_BULTO
		{
			get
			{
				return this._FL_FOL_OTD_BULTO;
			}
			set
			{
				if ((this._FL_FOL_OTD_BULTO != value))
				{
					this._FL_FOL_OTD_BULTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_PESO", DbType="Real")]
		public System.Nullable<float> FL_FOL_OTD_PESO
		{
			get
			{
				return this._FL_FOL_OTD_PESO;
			}
			set
			{
				if ((this._FL_FOL_OTD_PESO != value))
				{
					this._FL_FOL_OTD_PESO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESO_VOLUMETRICO", DbType="Real")]
		public System.Nullable<float> PESO_VOLUMETRICO
		{
			get
			{
				return this._PESO_VOLUMETRICO;
			}
			set
			{
				if ((this._PESO_VOLUMETRICO != value))
				{
					this._PESO_VOLUMETRICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_SER_FACTOR_VOLUMETRICO", DbType="Int")]
		public System.Nullable<int> FL_PAR_SER_FACTOR_VOLUMETRICO
		{
			get
			{
				return this._FL_PAR_SER_FACTOR_VOLUMETRICO;
			}
			set
			{
				if ((this._FL_PAR_SER_FACTOR_VOLUMETRICO != value))
				{
					this._FL_PAR_SER_FACTOR_VOLUMETRICO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESO_FACTURADO", DbType="Real")]
		public System.Nullable<float> PESO_FACTURADO
		{
			get
			{
				return this._PESO_FACTURADO;
			}
			set
			{
				if ((this._PESO_FACTURADO != value))
				{
					this._PESO_FACTURADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_SUC_NOMBRE_ORG", DbType="VarChar(200)")]
		public string FL_PAR_SUC_NOMBRE_ORG
		{
			get
			{
				return this._FL_PAR_SUC_NOMBRE_ORG;
			}
			set
			{
				if ((this._FL_PAR_SUC_NOMBRE_ORG != value))
				{
					this._FL_PAR_SUC_NOMBRE_ORG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_SUC_NOMBRE", DbType="VarChar(200)")]
		public string FL_PAR_SUC_NOMBRE
		{
			get
			{
				return this._FL_PAR_SUC_NOMBRE;
			}
			set
			{
				if ((this._FL_PAR_SUC_NOMBRE != value))
				{
					this._FL_PAR_SUC_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_FANTASIA", DbType="VarChar(100)")]
		public string FL_CLI_EMP_FANTASIA
		{
			get
			{
				return this._FL_CLI_EMP_FANTASIA;
			}
			set
			{
				if ((this._FL_CLI_EMP_FANTASIA != value))
				{
					this._FL_CLI_EMP_FANTASIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_SER_NOMBRE", DbType="VarChar(50)")]
		public string FL_PAR_SER_NOMBRE
		{
			get
			{
				return this._FL_PAR_SER_NOMBRE;
			}
			set
			{
				if ((this._FL_PAR_SER_NOMBRE != value))
				{
					this._FL_PAR_SER_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_DESTINATARIO_NOMBRE", DbType="VarChar(200)")]
		public string FL_FOL_OTD_DESTINATARIO_NOMBRE
		{
			get
			{
				return this._FL_FOL_OTD_DESTINATARIO_NOMBRE;
			}
			set
			{
				if ((this._FL_FOL_OTD_DESTINATARIO_NOMBRE != value))
				{
					this._FL_FOL_OTD_DESTINATARIO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_DESTINATARIO_RUT", DbType="VarChar(20)")]
		public string FL_FOL_OTD_DESTINATARIO_RUT
		{
			get
			{
				return this._FL_FOL_OTD_DESTINATARIO_RUT;
			}
			set
			{
				if ((this._FL_FOL_OTD_DESTINATARIO_RUT != value))
				{
					this._FL_FOL_OTD_DESTINATARIO_RUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_DESTINATARIO_DIRECCION", DbType="VarChar(200)")]
		public string FL_FOL_OTD_DESTINATARIO_DIRECCION
		{
			get
			{
				return this._FL_FOL_OTD_DESTINATARIO_DIRECCION;
			}
			set
			{
				if ((this._FL_FOL_OTD_DESTINATARIO_DIRECCION != value))
				{
					this._FL_FOL_OTD_DESTINATARIO_DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_DESTINATARIO_NUMERO", DbType="VarChar(50)")]
		public string FL_FOL_OTD_DESTINATARIO_NUMERO
		{
			get
			{
				return this._FL_FOL_OTD_DESTINATARIO_NUMERO;
			}
			set
			{
				if ((this._FL_FOL_OTD_DESTINATARIO_NUMERO != value))
				{
					this._FL_FOL_OTD_DESTINATARIO_NUMERO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_COM_NOMBRE", DbType="VarChar(40)")]
		public string FL_PAR_COM_NOMBRE
		{
			get
			{
				return this._FL_PAR_COM_NOMBRE;
			}
			set
			{
				if ((this._FL_PAR_COM_NOMBRE != value))
				{
					this._FL_PAR_COM_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_COM_CODIGO", DbType="VarChar(10)")]
		public string FL_PAR_COM_CODIGO
		{
			get
			{
				return this._FL_PAR_COM_CODIGO;
			}
			set
			{
				if ((this._FL_PAR_COM_CODIGO != value))
				{
					this._FL_PAR_COM_CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_TELEFONO", DbType="VarChar(100)")]
		public string FL_FOL_OTD_TELEFONO
		{
			get
			{
				return this._FL_FOL_OTD_TELEFONO;
			}
			set
			{
				if ((this._FL_FOL_OTD_TELEFONO != value))
				{
					this._FL_FOL_OTD_TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_CON_NOMBRE_T", DbType="VarChar(200)")]
		public string FL_PAR_CON_NOMBRE_T
		{
			get
			{
				return this._FL_PAR_CON_NOMBRE_T;
			}
			set
			{
				if ((this._FL_PAR_CON_NOMBRE_T != value))
				{
					this._FL_PAR_CON_NOMBRE_T = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_TRA_MODELO_T", DbType="VarChar(100)")]
		public string FL_PAR_TRA_MODELO_T
		{
			get
			{
				return this._FL_PAR_TRA_MODELO_T;
			}
			set
			{
				if ((this._FL_PAR_TRA_MODELO_T != value))
				{
					this._FL_PAR_TRA_MODELO_T = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_TRA_PATENTE_T", DbType="VarChar(20)")]
		public string FL_PAR_TRA_PATENTE_T
		{
			get
			{
				return this._FL_PAR_TRA_PATENTE_T;
			}
			set
			{
				if ((this._FL_PAR_TRA_PATENTE_T != value))
				{
					this._FL_PAR_TRA_PATENTE_T = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_CON_NOMBRE_S", DbType="VarChar(200)")]
		public string FL_PAR_CON_NOMBRE_S
		{
			get
			{
				return this._FL_PAR_CON_NOMBRE_S;
			}
			set
			{
				if ((this._FL_PAR_CON_NOMBRE_S != value))
				{
					this._FL_PAR_CON_NOMBRE_S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_TRA_MODELO_S", DbType="VarChar(100)")]
		public string FL_PAR_TRA_MODELO_S
		{
			get
			{
				return this._FL_PAR_TRA_MODELO_S;
			}
			set
			{
				if ((this._FL_PAR_TRA_MODELO_S != value))
				{
					this._FL_PAR_TRA_MODELO_S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_TRA_PATENTE_S", DbType="VarChar(20)")]
		public string FL_PAR_TRA_PATENTE_S
		{
			get
			{
				return this._FL_PAR_TRA_PATENTE_S;
			}
			set
			{
				if ((this._FL_PAR_TRA_PATENTE_S != value))
				{
					this._FL_PAR_TRA_PATENTE_S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_ENT_RECIBE", DbType="VarChar(200)")]
		public string FL_FOL_ENT_RECIBE
		{
			get
			{
				return this._FL_FOL_ENT_RECIBE;
			}
			set
			{
				if ((this._FL_FOL_ENT_RECIBE != value))
				{
					this._FL_FOL_ENT_RECIBE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_ENT_RUT", DbType="VarChar(20)")]
		public string FL_FOL_ENT_RUT
		{
			get
			{
				return this._FL_FOL_ENT_RUT;
			}
			set
			{
				if ((this._FL_FOL_ENT_RUT != value))
				{
					this._FL_FOL_ENT_RUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OTD_REFERENCIA2", DbType="VarChar(100)")]
		public string FL_FOL_OTD_REFERENCIA2
		{
			get
			{
				return this._FL_FOL_OTD_REFERENCIA2;
			}
			set
			{
				if ((this._FL_FOL_OTD_REFERENCIA2 != value))
				{
					this._FL_FOL_OTD_REFERENCIA2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_DES_DEV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TIPO_DES_DEV
		{
			get
			{
				return this._TIPO_DES_DEV;
			}
			set
			{
				if ((this._TIPO_DES_DEV != value))
				{
					this._TIPO_DES_DEV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_EDO_NOMBRE", DbType="VarChar(60)")]
		public string FL_FOL_EDO_NOMBRE
		{
			get
			{
				return this._FL_FOL_EDO_NOMBRE;
			}
			set
			{
				if ((this._FL_FOL_EDO_NOMBRE != value))
				{
					this._FL_FOL_EDO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_RDO_FECHA", DbType="VarChar(10)")]
		public string FL_FOL_RDO_FECHA
		{
			get
			{
				return this._FL_FOL_RDO_FECHA;
			}
			set
			{
				if ((this._FL_FOL_RDO_FECHA != value))
				{
					this._FL_FOL_RDO_FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fe_Gd_Estimada", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Fe_Gd_Estimada
		{
			get
			{
				return this._Fe_Gd_Estimada;
			}
			set
			{
				if ((this._Fe_Gd_Estimada != value))
				{
					this._Fe_Gd_Estimada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_PRIMERA_VISITA", DbType="VarChar(10)")]
		public string FL_FOL_PRIMERA_VISITA
		{
			get
			{
				return this._FL_FOL_PRIMERA_VISITA;
			}
			set
			{
				if ((this._FL_FOL_PRIMERA_VISITA != value))
				{
					this._FL_FOL_PRIMERA_VISITA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_PAR_VIA_NOMBRE", DbType="VarChar(20)")]
		public string FL_PAR_VIA_NOMBRE
		{
			get
			{
				return this._FL_PAR_VIA_NOMBRE;
			}
			set
			{
				if ((this._FL_PAR_VIA_NOMBRE != value))
				{
					this._FL_PAR_VIA_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTPadre", DbType="Decimal(18,0) NOT NULL")]
		public decimal OTPadre
		{
			get
			{
				return this._OTPadre;
			}
			set
			{
				if ((this._OTPadre != value))
				{
					this._OTPadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_DOA_CONTRAPAGO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FL_FOL_DOA_CONTRAPAGO
		{
			get
			{
				return this._FL_FOL_DOA_CONTRAPAGO;
			}
			set
			{
				if ((this._FL_FOL_DOA_CONTRAPAGO != value))
				{
					this._FL_FOL_DOA_CONTRAPAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_TOB_NOMBRE", DbType="VarChar(50)")]
		public string FL_FOL_TOB_NOMBRE
		{
			get
			{
				return this._FL_FOL_TOB_NOMBRE;
			}
			set
			{
				if ((this._FL_FOL_TOB_NOMBRE != value))
				{
					this._FL_FOL_TOB_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ULTIMO_ESTADO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string FECHA_ULTIMO_ESTADO
		{
			get
			{
				return this._FECHA_ULTIMO_ESTADO;
			}
			set
			{
				if ((this._FECHA_ULTIMO_ESTADO != value))
				{
					this._FECHA_ULTIMO_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBS_ULTIMO_ESTADO", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string OBS_ULTIMO_ESTADO
		{
			get
			{
				return this._OBS_ULTIMO_ESTADO;
			}
			set
			{
				if ((this._OBS_ULTIMO_ESTADO != value))
				{
					this._OBS_ULTIMO_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_FOL_OCA_OBSERVACION", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string FL_FOL_OCA_OBSERVACION
		{
			get
			{
				return this._FL_FOL_OCA_OBSERVACION;
			}
			set
			{
				if ((this._FL_FOL_OCA_OBSERVACION != value))
				{
					this._FL_FOL_OCA_OBSERVACION = value;
				}
			}
		}
	}
	
	public partial class PR_FOL_GRA_OTS_GRAL_DIAResult
	{
		
		private string _ESTADO;
		
		private System.Nullable<int> _CANTIDAD;
		
		public PR_FOL_GRA_OTS_GRAL_DIAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int")]
		public System.Nullable<int> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
	}
	
	public partial class PR_FOL_GRA_OTS_GRAL_DIA_DETALLEResult
	{
		
		private int _ESTADO;
		
		private string _OT;
		
		private string _CLIENTE;
		
		private string _CIUDAD;
		
		private string _ESTADO_OT;
		
		public PR_FOL_GRA_OTS_GRAL_DIA_DETALLEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int NOT NULL")]
		public int ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OT", DbType="VarChar(11)")]
		public string OT
		{
			get
			{
				return this._OT;
			}
			set
			{
				if ((this._OT != value))
				{
					this._OT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="VarChar(200)")]
		public string CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this._CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="VarChar(40)")]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this._CIUDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_OT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ESTADO_OT
		{
			get
			{
				return this._ESTADO_OT;
			}
			set
			{
				if ((this._ESTADO_OT != value))
				{
					this._ESTADO_OT = value;
				}
			}
		}
	}
	
	public partial class PR_FOL_GRA_OTS_GRAL_SERVICIOResult
	{
		
		private decimal _ID;
		
		private string _ESTADO;
		
		private string _SERVICIO;
		
		private System.Nullable<int> _CANTIDAD;
		
		public PR_FOL_GRA_OTS_GRAL_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO", DbType="VarChar(50)")]
		public string SERVICIO
		{
			get
			{
				return this._SERVICIO;
			}
			set
			{
				if ((this._SERVICIO != value))
				{
					this._SERVICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int")]
		public System.Nullable<int> CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
