#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_CLI_CLIENTES")]
	public partial class LinqCLIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP instance);
    partial void UpdateTB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP instance);
    partial void DeleteTB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP instance);
    partial void InsertTB_CLI_TPD_TIPO_DIRECCIONES(TB_CLI_TPD_TIPO_DIRECCIONES instance);
    partial void UpdateTB_CLI_TPD_TIPO_DIRECCIONES(TB_CLI_TPD_TIPO_DIRECCIONES instance);
    partial void DeleteTB_CLI_TPD_TIPO_DIRECCIONES(TB_CLI_TPD_TIPO_DIRECCIONES instance);
    partial void InsertTB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS instance);
    partial void UpdateTB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS instance);
    partial void DeleteTB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS instance);
    partial void InsertTB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP instance);
    partial void UpdateTB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP instance);
    partial void DeleteTB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP instance);
    partial void InsertTB_CLI_DIR_DIRECCIONES(TB_CLI_DIR_DIRECCIONES instance);
    partial void UpdateTB_CLI_DIR_DIRECCIONES(TB_CLI_DIR_DIRECCIONES instance);
    partial void DeleteTB_CLI_DIR_DIRECCIONES(TB_CLI_DIR_DIRECCIONES instance);
    partial void InsertTB_CLI_EMP_EMPRESAS(TB_CLI_EMP_EMPRESAS instance);
    partial void UpdateTB_CLI_EMP_EMPRESAS(TB_CLI_EMP_EMPRESAS instance);
    partial void DeleteTB_CLI_EMP_EMPRESAS(TB_CLI_EMP_EMPRESAS instance);
    partial void InsertTB_CLI_REC_REL_EMP_CTT(TB_CLI_REC_REL_EMP_CTT instance);
    partial void UpdateTB_CLI_REC_REL_EMP_CTT(TB_CLI_REC_REL_EMP_CTT instance);
    partial void DeleteTB_CLI_REC_REL_EMP_CTT(TB_CLI_REC_REL_EMP_CTT instance);
    partial void InsertTB_CLI_TCT_TIPO_CONTACTO(TB_CLI_TCT_TIPO_CONTACTO instance);
    partial void UpdateTB_CLI_TCT_TIPO_CONTACTO(TB_CLI_TCT_TIPO_CONTACTO instance);
    partial void DeleteTB_CLI_TCT_TIPO_CONTACTO(TB_CLI_TCT_TIPO_CONTACTO instance);
    partial void InsertTB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL instance);
    partial void UpdateTB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL instance);
    partial void DeleteTB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL instance);
    #endregion
		
		public LinqCLIDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_CLI_CLIENTESConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCLIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCLIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCLIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqCLIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_CLI_CEM_CTT_EMP> TB_CLI_CEM_CTT_EMP
		{
			get
			{
				return this.GetTable<TB_CLI_CEM_CTT_EMP>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_TPD_TIPO_DIRECCIONES> TB_CLI_TPD_TIPO_DIRECCIONES
		{
			get
			{
				return this.GetTable<TB_CLI_TPD_TIPO_DIRECCIONES>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_CTT_CONTACTOS> TB_CLI_CTT_CONTACTOS
		{
			get
			{
				return this.GetTable<TB_CLI_CTT_CONTACTOS>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_DEM_DIR_EMP> TB_CLI_DEM_DIR_EMP
		{
			get
			{
				return this.GetTable<TB_CLI_DEM_DIR_EMP>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_DIR_DIRECCIONES> TB_CLI_DIR_DIRECCIONES
		{
			get
			{
				return this.GetTable<TB_CLI_DIR_DIRECCIONES>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_EMP_EMPRESAS> TB_CLI_EMP_EMPRESAS
		{
			get
			{
				return this.GetTable<TB_CLI_EMP_EMPRESAS>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_REC_REL_EMP_CTT> TB_CLI_REC_REL_EMP_CTT
		{
			get
			{
				return this.GetTable<TB_CLI_REC_REL_EMP_CTT>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_TCT_TIPO_CONTACTO> TB_CLI_TCT_TIPO_CONTACTO
		{
			get
			{
				return this.GetTable<TB_CLI_TCT_TIPO_CONTACTO>();
			}
		}
		
		public System.Data.Linq.Table<TB_CLI_SUC_SUCURSAL> TB_CLI_SUC_SUCURSAL
		{
			get
			{
				return this.GetTable<TB_CLI_SUC_SUCURSAL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_CEM_CTT_EMP")]
	public partial class TB_CLI_CEM_CTT_EMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_EMP_RUT;
		
		private int _PK_CLI_CTT_RUT;
		
		private EntityRef<TB_CLI_CTT_CONTACTOS> _TB_CLI_CTT_CONTACTOS;
		
		private EntityRef<TB_CLI_EMP_EMPRESAS> _TB_CLI_EMP_EMPRESAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_EMP_RUTChanging(int value);
    partial void OnPK_CLI_EMP_RUTChanged();
    partial void OnPK_CLI_CTT_RUTChanging(int value);
    partial void OnPK_CLI_CTT_RUTChanged();
    #endregion
		
		public TB_CLI_CEM_CTT_EMP()
		{
			this._TB_CLI_CTT_CONTACTOS = default(EntityRef<TB_CLI_CTT_CONTACTOS>);
			this._TB_CLI_EMP_EMPRESAS = default(EntityRef<TB_CLI_EMP_EMPRESAS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_EMP_RUT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_EMP_RUT
		{
			get
			{
				return this._PK_CLI_EMP_RUT;
			}
			set
			{
				if ((this._PK_CLI_EMP_RUT != value))
				{
					if (this._TB_CLI_EMP_EMPRESAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_EMP_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_EMP_RUT = value;
					this.SendPropertyChanged("PK_CLI_EMP_RUT");
					this.OnPK_CLI_EMP_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_CTT_RUT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_CTT_RUT
		{
			get
			{
				return this._PK_CLI_CTT_RUT;
			}
			set
			{
				if ((this._PK_CLI_CTT_RUT != value))
				{
					if (this._TB_CLI_CTT_CONTACTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_CTT_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_CTT_RUT = value;
					this.SendPropertyChanged("PK_CLI_CTT_RUT");
					this.OnPK_CLI_CTT_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_CTT_CONTACTOS_TB_CLI_CEM_CTT_EMP", Storage="_TB_CLI_CTT_CONTACTOS", ThisKey="PK_CLI_CTT_RUT", OtherKey="PK_CLI_CTT_RUT", IsForeignKey=true)]
		public TB_CLI_CTT_CONTACTOS TB_CLI_CTT_CONTACTOS
		{
			get
			{
				return this._TB_CLI_CTT_CONTACTOS.Entity;
			}
			set
			{
				TB_CLI_CTT_CONTACTOS previousValue = this._TB_CLI_CTT_CONTACTOS.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_CTT_CONTACTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_CTT_CONTACTOS.Entity = null;
						previousValue.TB_CLI_CEM_CTT_EMP.Remove(this);
					}
					this._TB_CLI_CTT_CONTACTOS.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_CEM_CTT_EMP.Add(this);
						this._PK_CLI_CTT_RUT = value.PK_CLI_CTT_RUT;
					}
					else
					{
						this._PK_CLI_CTT_RUT = default(int);
					}
					this.SendPropertyChanged("TB_CLI_CTT_CONTACTOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_EMP_EMPRESAS_TB_CLI_CEM_CTT_EMP", Storage="_TB_CLI_EMP_EMPRESAS", ThisKey="PK_CLI_EMP_RUT", OtherKey="PK_CLI_EMP_RUT", IsForeignKey=true)]
		public TB_CLI_EMP_EMPRESAS TB_CLI_EMP_EMPRESAS
		{
			get
			{
				return this._TB_CLI_EMP_EMPRESAS.Entity;
			}
			set
			{
				TB_CLI_EMP_EMPRESAS previousValue = this._TB_CLI_EMP_EMPRESAS.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_EMP_EMPRESAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_EMP_EMPRESAS.Entity = null;
						previousValue.TB_CLI_CEM_CTT_EMP.Remove(this);
					}
					this._TB_CLI_EMP_EMPRESAS.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_CEM_CTT_EMP.Add(this);
						this._PK_CLI_EMP_RUT = value.PK_CLI_EMP_RUT;
					}
					else
					{
						this._PK_CLI_EMP_RUT = default(int);
					}
					this.SendPropertyChanged("TB_CLI_EMP_EMPRESAS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_TPD_TIPO_DIRECCIONES")]
	public partial class TB_CLI_TPD_TIPO_DIRECCIONES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_TPD_ID;
		
		private string _FL_CLI_TPD_NOMBRE;
		
		private EntitySet<TB_CLI_DIR_DIRECCIONES> _TB_CLI_DIR_DIRECCIONES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_TPD_IDChanging(int value);
    partial void OnPK_CLI_TPD_IDChanged();
    partial void OnFL_CLI_TPD_NOMBREChanging(string value);
    partial void OnFL_CLI_TPD_NOMBREChanged();
    #endregion
		
		public TB_CLI_TPD_TIPO_DIRECCIONES()
		{
			this._TB_CLI_DIR_DIRECCIONES = new EntitySet<TB_CLI_DIR_DIRECCIONES>(new Action<TB_CLI_DIR_DIRECCIONES>(this.attach_TB_CLI_DIR_DIRECCIONES), new Action<TB_CLI_DIR_DIRECCIONES>(this.detach_TB_CLI_DIR_DIRECCIONES));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_TPD_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_TPD_ID
		{
			get
			{
				return this._PK_CLI_TPD_ID;
			}
			set
			{
				if ((this._PK_CLI_TPD_ID != value))
				{
					this.OnPK_CLI_TPD_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_TPD_ID = value;
					this.SendPropertyChanged("PK_CLI_TPD_ID");
					this.OnPK_CLI_TPD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_TPD_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FL_CLI_TPD_NOMBRE
		{
			get
			{
				return this._FL_CLI_TPD_NOMBRE;
			}
			set
			{
				if ((this._FL_CLI_TPD_NOMBRE != value))
				{
					this.OnFL_CLI_TPD_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_TPD_NOMBRE = value;
					this.SendPropertyChanged("FL_CLI_TPD_NOMBRE");
					this.OnFL_CLI_TPD_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_TPD_TIPO_DIRECCIONES_TB_CLI_DIR_DIRECCIONES", Storage="_TB_CLI_DIR_DIRECCIONES", ThisKey="PK_CLI_TPD_ID", OtherKey="PK_CLI_TPD_ID")]
		public EntitySet<TB_CLI_DIR_DIRECCIONES> TB_CLI_DIR_DIRECCIONES
		{
			get
			{
				return this._TB_CLI_DIR_DIRECCIONES;
			}
			set
			{
				this._TB_CLI_DIR_DIRECCIONES.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CLI_DIR_DIRECCIONES(TB_CLI_DIR_DIRECCIONES entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_TPD_TIPO_DIRECCIONES = this;
		}
		
		private void detach_TB_CLI_DIR_DIRECCIONES(TB_CLI_DIR_DIRECCIONES entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_TPD_TIPO_DIRECCIONES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_CTT_CONTACTOS")]
	public partial class TB_CLI_CTT_CONTACTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_CTT_RUT;
		
		private string _FL_CLI_CTT_DV;
		
		private string _FL_CLI_CTT_NOMBRES;
		
		private string _FL_CLI_CTT_PATERNO;
		
		private string _FL_CLI_CTT_MATERNO;
		
		private string _FL_CLI_CTT_FONO1;
		
		private string _FL_CLI_CTT_FONO2;
		
		private string _FL_CLI_CTT_EMAIL;
		
		private System.Nullable<int> _PK_CLI_TCT_ID;
		
		private System.Nullable<int> _PK_CLI_DIR_ID;
		
		private EntitySet<TB_CLI_CEM_CTT_EMP> _TB_CLI_CEM_CTT_EMP;
		
		private EntityRef<TB_CLI_DIR_DIRECCIONES> _TB_CLI_DIR_DIRECCIONES;
		
		private EntityRef<TB_CLI_TCT_TIPO_CONTACTO> _TB_CLI_TCT_TIPO_CONTACTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_CTT_RUTChanging(int value);
    partial void OnPK_CLI_CTT_RUTChanged();
    partial void OnFL_CLI_CTT_DVChanging(string value);
    partial void OnFL_CLI_CTT_DVChanged();
    partial void OnFL_CLI_CTT_NOMBRESChanging(string value);
    partial void OnFL_CLI_CTT_NOMBRESChanged();
    partial void OnFL_CLI_CTT_PATERNOChanging(string value);
    partial void OnFL_CLI_CTT_PATERNOChanged();
    partial void OnFL_CLI_CTT_MATERNOChanging(string value);
    partial void OnFL_CLI_CTT_MATERNOChanged();
    partial void OnFL_CLI_CTT_FONO1Changing(string value);
    partial void OnFL_CLI_CTT_FONO1Changed();
    partial void OnFL_CLI_CTT_FONO2Changing(string value);
    partial void OnFL_CLI_CTT_FONO2Changed();
    partial void OnFL_CLI_CTT_EMAILChanging(string value);
    partial void OnFL_CLI_CTT_EMAILChanged();
    partial void OnPK_CLI_TCT_IDChanging(System.Nullable<int> value);
    partial void OnPK_CLI_TCT_IDChanged();
    partial void OnPK_CLI_DIR_IDChanging(System.Nullable<int> value);
    partial void OnPK_CLI_DIR_IDChanged();
    #endregion
		
		public TB_CLI_CTT_CONTACTOS()
		{
			this._TB_CLI_CEM_CTT_EMP = new EntitySet<TB_CLI_CEM_CTT_EMP>(new Action<TB_CLI_CEM_CTT_EMP>(this.attach_TB_CLI_CEM_CTT_EMP), new Action<TB_CLI_CEM_CTT_EMP>(this.detach_TB_CLI_CEM_CTT_EMP));
			this._TB_CLI_DIR_DIRECCIONES = default(EntityRef<TB_CLI_DIR_DIRECCIONES>);
			this._TB_CLI_TCT_TIPO_CONTACTO = default(EntityRef<TB_CLI_TCT_TIPO_CONTACTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_CTT_RUT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_CTT_RUT
		{
			get
			{
				return this._PK_CLI_CTT_RUT;
			}
			set
			{
				if ((this._PK_CLI_CTT_RUT != value))
				{
					this.OnPK_CLI_CTT_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_CTT_RUT = value;
					this.SendPropertyChanged("PK_CLI_CTT_RUT");
					this.OnPK_CLI_CTT_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_DV", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string FL_CLI_CTT_DV
		{
			get
			{
				return this._FL_CLI_CTT_DV;
			}
			set
			{
				if ((this._FL_CLI_CTT_DV != value))
				{
					this.OnFL_CLI_CTT_DVChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_DV = value;
					this.SendPropertyChanged("FL_CLI_CTT_DV");
					this.OnFL_CLI_CTT_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_NOMBRES", DbType="VarChar(50)")]
		public string FL_CLI_CTT_NOMBRES
		{
			get
			{
				return this._FL_CLI_CTT_NOMBRES;
			}
			set
			{
				if ((this._FL_CLI_CTT_NOMBRES != value))
				{
					this.OnFL_CLI_CTT_NOMBRESChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_NOMBRES = value;
					this.SendPropertyChanged("FL_CLI_CTT_NOMBRES");
					this.OnFL_CLI_CTT_NOMBRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_PATERNO", DbType="VarChar(50)")]
		public string FL_CLI_CTT_PATERNO
		{
			get
			{
				return this._FL_CLI_CTT_PATERNO;
			}
			set
			{
				if ((this._FL_CLI_CTT_PATERNO != value))
				{
					this.OnFL_CLI_CTT_PATERNOChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_PATERNO = value;
					this.SendPropertyChanged("FL_CLI_CTT_PATERNO");
					this.OnFL_CLI_CTT_PATERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_MATERNO", DbType="VarChar(50)")]
		public string FL_CLI_CTT_MATERNO
		{
			get
			{
				return this._FL_CLI_CTT_MATERNO;
			}
			set
			{
				if ((this._FL_CLI_CTT_MATERNO != value))
				{
					this.OnFL_CLI_CTT_MATERNOChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_MATERNO = value;
					this.SendPropertyChanged("FL_CLI_CTT_MATERNO");
					this.OnFL_CLI_CTT_MATERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_FONO1", DbType="VarChar(10)")]
		public string FL_CLI_CTT_FONO1
		{
			get
			{
				return this._FL_CLI_CTT_FONO1;
			}
			set
			{
				if ((this._FL_CLI_CTT_FONO1 != value))
				{
					this.OnFL_CLI_CTT_FONO1Changing(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_FONO1 = value;
					this.SendPropertyChanged("FL_CLI_CTT_FONO1");
					this.OnFL_CLI_CTT_FONO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_FONO2", DbType="VarChar(10)")]
		public string FL_CLI_CTT_FONO2
		{
			get
			{
				return this._FL_CLI_CTT_FONO2;
			}
			set
			{
				if ((this._FL_CLI_CTT_FONO2 != value))
				{
					this.OnFL_CLI_CTT_FONO2Changing(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_FONO2 = value;
					this.SendPropertyChanged("FL_CLI_CTT_FONO2");
					this.OnFL_CLI_CTT_FONO2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_CTT_EMAIL", DbType="VarChar(50)")]
		public string FL_CLI_CTT_EMAIL
		{
			get
			{
				return this._FL_CLI_CTT_EMAIL;
			}
			set
			{
				if ((this._FL_CLI_CTT_EMAIL != value))
				{
					this.OnFL_CLI_CTT_EMAILChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_CTT_EMAIL = value;
					this.SendPropertyChanged("FL_CLI_CTT_EMAIL");
					this.OnFL_CLI_CTT_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_TCT_ID", DbType="Int")]
		public System.Nullable<int> PK_CLI_TCT_ID
		{
			get
			{
				return this._PK_CLI_TCT_ID;
			}
			set
			{
				if ((this._PK_CLI_TCT_ID != value))
				{
					if (this._TB_CLI_TCT_TIPO_CONTACTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_TCT_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_TCT_ID = value;
					this.SendPropertyChanged("PK_CLI_TCT_ID");
					this.OnPK_CLI_TCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_DIR_ID", DbType="Int")]
		public System.Nullable<int> PK_CLI_DIR_ID
		{
			get
			{
				return this._PK_CLI_DIR_ID;
			}
			set
			{
				if ((this._PK_CLI_DIR_ID != value))
				{
					if (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_DIR_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_DIR_ID = value;
					this.SendPropertyChanged("PK_CLI_DIR_ID");
					this.OnPK_CLI_DIR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_CTT_CONTACTOS_TB_CLI_CEM_CTT_EMP", Storage="_TB_CLI_CEM_CTT_EMP", ThisKey="PK_CLI_CTT_RUT", OtherKey="PK_CLI_CTT_RUT")]
		public EntitySet<TB_CLI_CEM_CTT_EMP> TB_CLI_CEM_CTT_EMP
		{
			get
			{
				return this._TB_CLI_CEM_CTT_EMP;
			}
			set
			{
				this._TB_CLI_CEM_CTT_EMP.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_CTT_CONTACTOS", Storage="_TB_CLI_DIR_DIRECCIONES", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID", IsForeignKey=true)]
		public TB_CLI_DIR_DIRECCIONES TB_CLI_DIR_DIRECCIONES
		{
			get
			{
				return this._TB_CLI_DIR_DIRECCIONES.Entity;
			}
			set
			{
				TB_CLI_DIR_DIRECCIONES previousValue = this._TB_CLI_DIR_DIRECCIONES.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_DIR_DIRECCIONES.Entity = null;
						previousValue.TB_CLI_CTT_CONTACTOS.Remove(this);
					}
					this._TB_CLI_DIR_DIRECCIONES.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_CTT_CONTACTOS.Add(this);
						this._PK_CLI_DIR_ID = value.PK_CLI_DIR_ID;
					}
					else
					{
						this._PK_CLI_DIR_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_CLI_DIR_DIRECCIONES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_TCT_TIPO_CONTACTO_TB_CLI_CTT_CONTACTOS", Storage="_TB_CLI_TCT_TIPO_CONTACTO", ThisKey="PK_CLI_TCT_ID", OtherKey="PK_CLI_TCT_ID", IsForeignKey=true)]
		public TB_CLI_TCT_TIPO_CONTACTO TB_CLI_TCT_TIPO_CONTACTO
		{
			get
			{
				return this._TB_CLI_TCT_TIPO_CONTACTO.Entity;
			}
			set
			{
				TB_CLI_TCT_TIPO_CONTACTO previousValue = this._TB_CLI_TCT_TIPO_CONTACTO.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_TCT_TIPO_CONTACTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_TCT_TIPO_CONTACTO.Entity = null;
						previousValue.TB_CLI_CTT_CONTACTOS.Remove(this);
					}
					this._TB_CLI_TCT_TIPO_CONTACTO.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_CTT_CONTACTOS.Add(this);
						this._PK_CLI_TCT_ID = value.PK_CLI_TCT_ID;
					}
					else
					{
						this._PK_CLI_TCT_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_CLI_TCT_TIPO_CONTACTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_CTT_CONTACTOS = this;
		}
		
		private void detach_TB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_CTT_CONTACTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_DEM_DIR_EMP")]
	public partial class TB_CLI_DEM_DIR_EMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_EMP_RUT;
		
		private int _PK_CLI_DIR_ID;
		
		private EntityRef<TB_CLI_DIR_DIRECCIONES> _TB_CLI_DIR_DIRECCIONES;
		
		private EntityRef<TB_CLI_EMP_EMPRESAS> _TB_CLI_EMP_EMPRESAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_EMP_RUTChanging(int value);
    partial void OnPK_CLI_EMP_RUTChanged();
    partial void OnPK_CLI_DIR_IDChanging(int value);
    partial void OnPK_CLI_DIR_IDChanged();
    #endregion
		
		public TB_CLI_DEM_DIR_EMP()
		{
			this._TB_CLI_DIR_DIRECCIONES = default(EntityRef<TB_CLI_DIR_DIRECCIONES>);
			this._TB_CLI_EMP_EMPRESAS = default(EntityRef<TB_CLI_EMP_EMPRESAS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_EMP_RUT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_EMP_RUT
		{
			get
			{
				return this._PK_CLI_EMP_RUT;
			}
			set
			{
				if ((this._PK_CLI_EMP_RUT != value))
				{
					if (this._TB_CLI_EMP_EMPRESAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_EMP_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_EMP_RUT = value;
					this.SendPropertyChanged("PK_CLI_EMP_RUT");
					this.OnPK_CLI_EMP_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_DIR_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_DIR_ID
		{
			get
			{
				return this._PK_CLI_DIR_ID;
			}
			set
			{
				if ((this._PK_CLI_DIR_ID != value))
				{
					if (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_DIR_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_DIR_ID = value;
					this.SendPropertyChanged("PK_CLI_DIR_ID");
					this.OnPK_CLI_DIR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_DEM_DIR_EMP", Storage="_TB_CLI_DIR_DIRECCIONES", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID", IsForeignKey=true)]
		public TB_CLI_DIR_DIRECCIONES TB_CLI_DIR_DIRECCIONES
		{
			get
			{
				return this._TB_CLI_DIR_DIRECCIONES.Entity;
			}
			set
			{
				TB_CLI_DIR_DIRECCIONES previousValue = this._TB_CLI_DIR_DIRECCIONES.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_DIR_DIRECCIONES.Entity = null;
						previousValue.TB_CLI_DEM_DIR_EMP.Remove(this);
					}
					this._TB_CLI_DIR_DIRECCIONES.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_DEM_DIR_EMP.Add(this);
						this._PK_CLI_DIR_ID = value.PK_CLI_DIR_ID;
					}
					else
					{
						this._PK_CLI_DIR_ID = default(int);
					}
					this.SendPropertyChanged("TB_CLI_DIR_DIRECCIONES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_EMP_EMPRESAS_TB_CLI_DEM_DIR_EMP", Storage="_TB_CLI_EMP_EMPRESAS", ThisKey="PK_CLI_EMP_RUT", OtherKey="PK_CLI_EMP_RUT", IsForeignKey=true)]
		public TB_CLI_EMP_EMPRESAS TB_CLI_EMP_EMPRESAS
		{
			get
			{
				return this._TB_CLI_EMP_EMPRESAS.Entity;
			}
			set
			{
				TB_CLI_EMP_EMPRESAS previousValue = this._TB_CLI_EMP_EMPRESAS.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_EMP_EMPRESAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_EMP_EMPRESAS.Entity = null;
						previousValue.TB_CLI_DEM_DIR_EMP.Remove(this);
					}
					this._TB_CLI_EMP_EMPRESAS.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_DEM_DIR_EMP.Add(this);
						this._PK_CLI_EMP_RUT = value.PK_CLI_EMP_RUT;
					}
					else
					{
						this._PK_CLI_EMP_RUT = default(int);
					}
					this.SendPropertyChanged("TB_CLI_EMP_EMPRESAS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_DIR_DIRECCIONES")]
	public partial class TB_CLI_DIR_DIRECCIONES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_DIR_ID;
		
		private int _PK_CLI_TPD_ID;
		
		private string _FL_CLI_DIR_DIRECCION;
		
		private int _PK_PAR_COM_ID;
		
		private EntitySet<TB_CLI_CTT_CONTACTOS> _TB_CLI_CTT_CONTACTOS;
		
		private EntitySet<TB_CLI_DEM_DIR_EMP> _TB_CLI_DEM_DIR_EMP;
		
		private EntitySet<TB_CLI_EMP_EMPRESAS> _TB_CLI_EMP_EMPRESAS;
		
		private EntitySet<TB_CLI_SUC_SUCURSAL> _TB_CLI_SUC_SUCURSAL;
		
		private EntityRef<TB_CLI_TPD_TIPO_DIRECCIONES> _TB_CLI_TPD_TIPO_DIRECCIONES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_DIR_IDChanging(int value);
    partial void OnPK_CLI_DIR_IDChanged();
    partial void OnPK_CLI_TPD_IDChanging(int value);
    partial void OnPK_CLI_TPD_IDChanged();
    partial void OnFL_CLI_DIR_DIRECCIONChanging(string value);
    partial void OnFL_CLI_DIR_DIRECCIONChanged();
    partial void OnPK_PAR_COM_IDChanging(int value);
    partial void OnPK_PAR_COM_IDChanged();
    #endregion
		
		public TB_CLI_DIR_DIRECCIONES()
		{
			this._TB_CLI_CTT_CONTACTOS = new EntitySet<TB_CLI_CTT_CONTACTOS>(new Action<TB_CLI_CTT_CONTACTOS>(this.attach_TB_CLI_CTT_CONTACTOS), new Action<TB_CLI_CTT_CONTACTOS>(this.detach_TB_CLI_CTT_CONTACTOS));
			this._TB_CLI_DEM_DIR_EMP = new EntitySet<TB_CLI_DEM_DIR_EMP>(new Action<TB_CLI_DEM_DIR_EMP>(this.attach_TB_CLI_DEM_DIR_EMP), new Action<TB_CLI_DEM_DIR_EMP>(this.detach_TB_CLI_DEM_DIR_EMP));
			this._TB_CLI_EMP_EMPRESAS = new EntitySet<TB_CLI_EMP_EMPRESAS>(new Action<TB_CLI_EMP_EMPRESAS>(this.attach_TB_CLI_EMP_EMPRESAS), new Action<TB_CLI_EMP_EMPRESAS>(this.detach_TB_CLI_EMP_EMPRESAS));
			this._TB_CLI_SUC_SUCURSAL = new EntitySet<TB_CLI_SUC_SUCURSAL>(new Action<TB_CLI_SUC_SUCURSAL>(this.attach_TB_CLI_SUC_SUCURSAL), new Action<TB_CLI_SUC_SUCURSAL>(this.detach_TB_CLI_SUC_SUCURSAL));
			this._TB_CLI_TPD_TIPO_DIRECCIONES = default(EntityRef<TB_CLI_TPD_TIPO_DIRECCIONES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_DIR_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_CLI_DIR_ID
		{
			get
			{
				return this._PK_CLI_DIR_ID;
			}
			set
			{
				if ((this._PK_CLI_DIR_ID != value))
				{
					this.OnPK_CLI_DIR_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_DIR_ID = value;
					this.SendPropertyChanged("PK_CLI_DIR_ID");
					this.OnPK_CLI_DIR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_TPD_ID", DbType="Int NOT NULL")]
		public int PK_CLI_TPD_ID
		{
			get
			{
				return this._PK_CLI_TPD_ID;
			}
			set
			{
				if ((this._PK_CLI_TPD_ID != value))
				{
					if (this._TB_CLI_TPD_TIPO_DIRECCIONES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_TPD_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_TPD_ID = value;
					this.SendPropertyChanged("PK_CLI_TPD_ID");
					this.OnPK_CLI_TPD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_DIR_DIRECCION", DbType="VarChar(200)")]
		public string FL_CLI_DIR_DIRECCION
		{
			get
			{
				return this._FL_CLI_DIR_DIRECCION;
			}
			set
			{
				if ((this._FL_CLI_DIR_DIRECCION != value))
				{
					this.OnFL_CLI_DIR_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_DIR_DIRECCION = value;
					this.SendPropertyChanged("FL_CLI_DIR_DIRECCION");
					this.OnFL_CLI_DIR_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_PAR_COM_ID", DbType="Int NOT NULL")]
		public int PK_PAR_COM_ID
		{
			get
			{
				return this._PK_PAR_COM_ID;
			}
			set
			{
				if ((this._PK_PAR_COM_ID != value))
				{
					this.OnPK_PAR_COM_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_PAR_COM_ID = value;
					this.SendPropertyChanged("PK_PAR_COM_ID");
					this.OnPK_PAR_COM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_CTT_CONTACTOS", Storage="_TB_CLI_CTT_CONTACTOS", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID")]
		public EntitySet<TB_CLI_CTT_CONTACTOS> TB_CLI_CTT_CONTACTOS
		{
			get
			{
				return this._TB_CLI_CTT_CONTACTOS;
			}
			set
			{
				this._TB_CLI_CTT_CONTACTOS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_DEM_DIR_EMP", Storage="_TB_CLI_DEM_DIR_EMP", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID")]
		public EntitySet<TB_CLI_DEM_DIR_EMP> TB_CLI_DEM_DIR_EMP
		{
			get
			{
				return this._TB_CLI_DEM_DIR_EMP;
			}
			set
			{
				this._TB_CLI_DEM_DIR_EMP.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_EMP_EMPRESAS", Storage="_TB_CLI_EMP_EMPRESAS", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID")]
		public EntitySet<TB_CLI_EMP_EMPRESAS> TB_CLI_EMP_EMPRESAS
		{
			get
			{
				return this._TB_CLI_EMP_EMPRESAS;
			}
			set
			{
				this._TB_CLI_EMP_EMPRESAS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_SUC_SUCURSAL", Storage="_TB_CLI_SUC_SUCURSAL", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID")]
		public EntitySet<TB_CLI_SUC_SUCURSAL> TB_CLI_SUC_SUCURSAL
		{
			get
			{
				return this._TB_CLI_SUC_SUCURSAL;
			}
			set
			{
				this._TB_CLI_SUC_SUCURSAL.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_TPD_TIPO_DIRECCIONES_TB_CLI_DIR_DIRECCIONES", Storage="_TB_CLI_TPD_TIPO_DIRECCIONES", ThisKey="PK_CLI_TPD_ID", OtherKey="PK_CLI_TPD_ID", IsForeignKey=true)]
		public TB_CLI_TPD_TIPO_DIRECCIONES TB_CLI_TPD_TIPO_DIRECCIONES
		{
			get
			{
				return this._TB_CLI_TPD_TIPO_DIRECCIONES.Entity;
			}
			set
			{
				TB_CLI_TPD_TIPO_DIRECCIONES previousValue = this._TB_CLI_TPD_TIPO_DIRECCIONES.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_TPD_TIPO_DIRECCIONES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_TPD_TIPO_DIRECCIONES.Entity = null;
						previousValue.TB_CLI_DIR_DIRECCIONES.Remove(this);
					}
					this._TB_CLI_TPD_TIPO_DIRECCIONES.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_DIR_DIRECCIONES.Add(this);
						this._PK_CLI_TPD_ID = value.PK_CLI_TPD_ID;
					}
					else
					{
						this._PK_CLI_TPD_ID = default(int);
					}
					this.SendPropertyChanged("TB_CLI_TPD_TIPO_DIRECCIONES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = this;
		}
		
		private void detach_TB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = null;
		}
		
		private void attach_TB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = this;
		}
		
		private void detach_TB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = null;
		}
		
		private void attach_TB_CLI_EMP_EMPRESAS(TB_CLI_EMP_EMPRESAS entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = this;
		}
		
		private void detach_TB_CLI_EMP_EMPRESAS(TB_CLI_EMP_EMPRESAS entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = null;
		}
		
		private void attach_TB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = this;
		}
		
		private void detach_TB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_DIR_DIRECCIONES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_EMP_EMPRESAS")]
	public partial class TB_CLI_EMP_EMPRESAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_EMP_RUT;
		
		private string _FL_CLI_EMP_DV;
		
		private string _FL_CLI_EMP_RAZON_SOCIAL;
		
		private string _FL_CLI_EMP_FANTASIA;
		
		private string _FL_CLI_EMP_GIRO_COMERCIAL;
		
		private int _FL_CLI_EMP_ACTIVO;
		
		private System.Nullable<int> _PK_CLI_DIR_ID;
		
		private System.Nullable<int> _FL_CLI_EMP_CODIGO_POSTAL;
		
		private System.Nullable<System.DateTime> _FL_CLI_EMP_FECHA_INGRESO;
		
		private EntitySet<TB_CLI_CEM_CTT_EMP> _TB_CLI_CEM_CTT_EMP;
		
		private EntitySet<TB_CLI_DEM_DIR_EMP> _TB_CLI_DEM_DIR_EMP;
		
		private EntitySet<TB_CLI_SUC_SUCURSAL> _TB_CLI_SUC_SUCURSAL;
		
		private EntityRef<TB_CLI_DIR_DIRECCIONES> _TB_CLI_DIR_DIRECCIONES;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_EMP_RUTChanging(int value);
    partial void OnPK_CLI_EMP_RUTChanged();
    partial void OnFL_CLI_EMP_DVChanging(string value);
    partial void OnFL_CLI_EMP_DVChanged();
    partial void OnFL_CLI_EMP_RAZON_SOCIALChanging(string value);
    partial void OnFL_CLI_EMP_RAZON_SOCIALChanged();
    partial void OnFL_CLI_EMP_FANTASIAChanging(string value);
    partial void OnFL_CLI_EMP_FANTASIAChanged();
    partial void OnFL_CLI_EMP_GIRO_COMERCIALChanging(string value);
    partial void OnFL_CLI_EMP_GIRO_COMERCIALChanged();
    partial void OnFL_CLI_EMP_ACTIVOChanging(int value);
    partial void OnFL_CLI_EMP_ACTIVOChanged();
    partial void OnPK_CLI_DIR_IDChanging(System.Nullable<int> value);
    partial void OnPK_CLI_DIR_IDChanged();
    partial void OnFL_CLI_EMP_CODIGO_POSTALChanging(System.Nullable<int> value);
    partial void OnFL_CLI_EMP_CODIGO_POSTALChanged();
    partial void OnFL_CLI_EMP_FECHA_INGRESOChanging(System.Nullable<System.DateTime> value);
    partial void OnFL_CLI_EMP_FECHA_INGRESOChanged();
    #endregion
		
		public TB_CLI_EMP_EMPRESAS()
		{
			this._TB_CLI_CEM_CTT_EMP = new EntitySet<TB_CLI_CEM_CTT_EMP>(new Action<TB_CLI_CEM_CTT_EMP>(this.attach_TB_CLI_CEM_CTT_EMP), new Action<TB_CLI_CEM_CTT_EMP>(this.detach_TB_CLI_CEM_CTT_EMP));
			this._TB_CLI_DEM_DIR_EMP = new EntitySet<TB_CLI_DEM_DIR_EMP>(new Action<TB_CLI_DEM_DIR_EMP>(this.attach_TB_CLI_DEM_DIR_EMP), new Action<TB_CLI_DEM_DIR_EMP>(this.detach_TB_CLI_DEM_DIR_EMP));
			this._TB_CLI_SUC_SUCURSAL = new EntitySet<TB_CLI_SUC_SUCURSAL>(new Action<TB_CLI_SUC_SUCURSAL>(this.attach_TB_CLI_SUC_SUCURSAL), new Action<TB_CLI_SUC_SUCURSAL>(this.detach_TB_CLI_SUC_SUCURSAL));
			this._TB_CLI_DIR_DIRECCIONES = default(EntityRef<TB_CLI_DIR_DIRECCIONES>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_EMP_RUT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_EMP_RUT
		{
			get
			{
				return this._PK_CLI_EMP_RUT;
			}
			set
			{
				if ((this._PK_CLI_EMP_RUT != value))
				{
					this.OnPK_CLI_EMP_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_EMP_RUT = value;
					this.SendPropertyChanged("PK_CLI_EMP_RUT");
					this.OnPK_CLI_EMP_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_DV", DbType="VarChar(1)")]
		public string FL_CLI_EMP_DV
		{
			get
			{
				return this._FL_CLI_EMP_DV;
			}
			set
			{
				if ((this._FL_CLI_EMP_DV != value))
				{
					this.OnFL_CLI_EMP_DVChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_DV = value;
					this.SendPropertyChanged("FL_CLI_EMP_DV");
					this.OnFL_CLI_EMP_DVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_RAZON_SOCIAL", DbType="VarChar(100)")]
		public string FL_CLI_EMP_RAZON_SOCIAL
		{
			get
			{
				return this._FL_CLI_EMP_RAZON_SOCIAL;
			}
			set
			{
				if ((this._FL_CLI_EMP_RAZON_SOCIAL != value))
				{
					this.OnFL_CLI_EMP_RAZON_SOCIALChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_RAZON_SOCIAL = value;
					this.SendPropertyChanged("FL_CLI_EMP_RAZON_SOCIAL");
					this.OnFL_CLI_EMP_RAZON_SOCIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_FANTASIA", DbType="VarChar(100)")]
		public string FL_CLI_EMP_FANTASIA
		{
			get
			{
				return this._FL_CLI_EMP_FANTASIA;
			}
			set
			{
				if ((this._FL_CLI_EMP_FANTASIA != value))
				{
					this.OnFL_CLI_EMP_FANTASIAChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_FANTASIA = value;
					this.SendPropertyChanged("FL_CLI_EMP_FANTASIA");
					this.OnFL_CLI_EMP_FANTASIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_GIRO_COMERCIAL", DbType="VarChar(100)")]
		public string FL_CLI_EMP_GIRO_COMERCIAL
		{
			get
			{
				return this._FL_CLI_EMP_GIRO_COMERCIAL;
			}
			set
			{
				if ((this._FL_CLI_EMP_GIRO_COMERCIAL != value))
				{
					this.OnFL_CLI_EMP_GIRO_COMERCIALChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_GIRO_COMERCIAL = value;
					this.SendPropertyChanged("FL_CLI_EMP_GIRO_COMERCIAL");
					this.OnFL_CLI_EMP_GIRO_COMERCIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_ACTIVO", DbType="Int NOT NULL")]
		public int FL_CLI_EMP_ACTIVO
		{
			get
			{
				return this._FL_CLI_EMP_ACTIVO;
			}
			set
			{
				if ((this._FL_CLI_EMP_ACTIVO != value))
				{
					this.OnFL_CLI_EMP_ACTIVOChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_ACTIVO = value;
					this.SendPropertyChanged("FL_CLI_EMP_ACTIVO");
					this.OnFL_CLI_EMP_ACTIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_DIR_ID", DbType="Int")]
		public System.Nullable<int> PK_CLI_DIR_ID
		{
			get
			{
				return this._PK_CLI_DIR_ID;
			}
			set
			{
				if ((this._PK_CLI_DIR_ID != value))
				{
					if (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_DIR_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_DIR_ID = value;
					this.SendPropertyChanged("PK_CLI_DIR_ID");
					this.OnPK_CLI_DIR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_CODIGO_POSTAL", DbType="Int")]
		public System.Nullable<int> FL_CLI_EMP_CODIGO_POSTAL
		{
			get
			{
				return this._FL_CLI_EMP_CODIGO_POSTAL;
			}
			set
			{
				if ((this._FL_CLI_EMP_CODIGO_POSTAL != value))
				{
					this.OnFL_CLI_EMP_CODIGO_POSTALChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_CODIGO_POSTAL = value;
					this.SendPropertyChanged("FL_CLI_EMP_CODIGO_POSTAL");
					this.OnFL_CLI_EMP_CODIGO_POSTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_EMP_FECHA_INGRESO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FL_CLI_EMP_FECHA_INGRESO
		{
			get
			{
				return this._FL_CLI_EMP_FECHA_INGRESO;
			}
			set
			{
				if ((this._FL_CLI_EMP_FECHA_INGRESO != value))
				{
					this.OnFL_CLI_EMP_FECHA_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_EMP_FECHA_INGRESO = value;
					this.SendPropertyChanged("FL_CLI_EMP_FECHA_INGRESO");
					this.OnFL_CLI_EMP_FECHA_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_EMP_EMPRESAS_TB_CLI_CEM_CTT_EMP", Storage="_TB_CLI_CEM_CTT_EMP", ThisKey="PK_CLI_EMP_RUT", OtherKey="PK_CLI_EMP_RUT")]
		public EntitySet<TB_CLI_CEM_CTT_EMP> TB_CLI_CEM_CTT_EMP
		{
			get
			{
				return this._TB_CLI_CEM_CTT_EMP;
			}
			set
			{
				this._TB_CLI_CEM_CTT_EMP.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_EMP_EMPRESAS_TB_CLI_DEM_DIR_EMP", Storage="_TB_CLI_DEM_DIR_EMP", ThisKey="PK_CLI_EMP_RUT", OtherKey="PK_CLI_EMP_RUT")]
		public EntitySet<TB_CLI_DEM_DIR_EMP> TB_CLI_DEM_DIR_EMP
		{
			get
			{
				return this._TB_CLI_DEM_DIR_EMP;
			}
			set
			{
				this._TB_CLI_DEM_DIR_EMP.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_EMP_EMPRESAS_TB_CLI_SUC_SUCURSAL", Storage="_TB_CLI_SUC_SUCURSAL", ThisKey="PK_CLI_EMP_RUT", OtherKey="PK_CLI_EMP_RUT")]
		public EntitySet<TB_CLI_SUC_SUCURSAL> TB_CLI_SUC_SUCURSAL
		{
			get
			{
				return this._TB_CLI_SUC_SUCURSAL;
			}
			set
			{
				this._TB_CLI_SUC_SUCURSAL.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_EMP_EMPRESAS", Storage="_TB_CLI_DIR_DIRECCIONES", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID", IsForeignKey=true)]
		public TB_CLI_DIR_DIRECCIONES TB_CLI_DIR_DIRECCIONES
		{
			get
			{
				return this._TB_CLI_DIR_DIRECCIONES.Entity;
			}
			set
			{
				TB_CLI_DIR_DIRECCIONES previousValue = this._TB_CLI_DIR_DIRECCIONES.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_DIR_DIRECCIONES.Entity = null;
						previousValue.TB_CLI_EMP_EMPRESAS.Remove(this);
					}
					this._TB_CLI_DIR_DIRECCIONES.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_EMP_EMPRESAS.Add(this);
						this._PK_CLI_DIR_ID = value.PK_CLI_DIR_ID;
					}
					else
					{
						this._PK_CLI_DIR_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_CLI_DIR_DIRECCIONES");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_EMP_EMPRESAS = this;
		}
		
		private void detach_TB_CLI_CEM_CTT_EMP(TB_CLI_CEM_CTT_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_EMP_EMPRESAS = null;
		}
		
		private void attach_TB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_EMP_EMPRESAS = this;
		}
		
		private void detach_TB_CLI_DEM_DIR_EMP(TB_CLI_DEM_DIR_EMP entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_EMP_EMPRESAS = null;
		}
		
		private void attach_TB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_EMP_EMPRESAS = this;
		}
		
		private void detach_TB_CLI_SUC_SUCURSAL(TB_CLI_SUC_SUCURSAL entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_EMP_EMPRESAS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_REC_REL_EMP_CTT")]
	public partial class TB_CLI_REC_REL_EMP_CTT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_CTT_RUT;
		
		private int _PK_CLI_TCT_ID;
		
		private int _PK_CLI_DIR_ID;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_CTT_RUTChanging(int value);
    partial void OnPK_CLI_CTT_RUTChanged();
    partial void OnPK_CLI_TCT_IDChanging(int value);
    partial void OnPK_CLI_TCT_IDChanged();
    partial void OnPK_CLI_DIR_IDChanging(int value);
    partial void OnPK_CLI_DIR_IDChanged();
    #endregion
		
		public TB_CLI_REC_REL_EMP_CTT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_CTT_RUT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_CTT_RUT
		{
			get
			{
				return this._PK_CLI_CTT_RUT;
			}
			set
			{
				if ((this._PK_CLI_CTT_RUT != value))
				{
					this.OnPK_CLI_CTT_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_CTT_RUT = value;
					this.SendPropertyChanged("PK_CLI_CTT_RUT");
					this.OnPK_CLI_CTT_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_TCT_ID", DbType="Int NOT NULL")]
		public int PK_CLI_TCT_ID
		{
			get
			{
				return this._PK_CLI_TCT_ID;
			}
			set
			{
				if ((this._PK_CLI_TCT_ID != value))
				{
					this.OnPK_CLI_TCT_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_TCT_ID = value;
					this.SendPropertyChanged("PK_CLI_TCT_ID");
					this.OnPK_CLI_TCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_DIR_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_CLI_DIR_ID
		{
			get
			{
				return this._PK_CLI_DIR_ID;
			}
			set
			{
				if ((this._PK_CLI_DIR_ID != value))
				{
					this.OnPK_CLI_DIR_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_DIR_ID = value;
					this.SendPropertyChanged("PK_CLI_DIR_ID");
					this.OnPK_CLI_DIR_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_TCT_TIPO_CONTACTO")]
	public partial class TB_CLI_TCT_TIPO_CONTACTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_TCT_ID;
		
		private string _FL_CLI_TCT_NOMBRE;
		
		private EntitySet<TB_CLI_CTT_CONTACTOS> _TB_CLI_CTT_CONTACTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_TCT_IDChanging(int value);
    partial void OnPK_CLI_TCT_IDChanged();
    partial void OnFL_CLI_TCT_NOMBREChanging(string value);
    partial void OnFL_CLI_TCT_NOMBREChanged();
    #endregion
		
		public TB_CLI_TCT_TIPO_CONTACTO()
		{
			this._TB_CLI_CTT_CONTACTOS = new EntitySet<TB_CLI_CTT_CONTACTOS>(new Action<TB_CLI_CTT_CONTACTOS>(this.attach_TB_CLI_CTT_CONTACTOS), new Action<TB_CLI_CTT_CONTACTOS>(this.detach_TB_CLI_CTT_CONTACTOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_TCT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_CLI_TCT_ID
		{
			get
			{
				return this._PK_CLI_TCT_ID;
			}
			set
			{
				if ((this._PK_CLI_TCT_ID != value))
				{
					this.OnPK_CLI_TCT_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_TCT_ID = value;
					this.SendPropertyChanged("PK_CLI_TCT_ID");
					this.OnPK_CLI_TCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_TCT_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FL_CLI_TCT_NOMBRE
		{
			get
			{
				return this._FL_CLI_TCT_NOMBRE;
			}
			set
			{
				if ((this._FL_CLI_TCT_NOMBRE != value))
				{
					this.OnFL_CLI_TCT_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_TCT_NOMBRE = value;
					this.SendPropertyChanged("FL_CLI_TCT_NOMBRE");
					this.OnFL_CLI_TCT_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_TCT_TIPO_CONTACTO_TB_CLI_CTT_CONTACTOS", Storage="_TB_CLI_CTT_CONTACTOS", ThisKey="PK_CLI_TCT_ID", OtherKey="PK_CLI_TCT_ID")]
		public EntitySet<TB_CLI_CTT_CONTACTOS> TB_CLI_CTT_CONTACTOS
		{
			get
			{
				return this._TB_CLI_CTT_CONTACTOS;
			}
			set
			{
				this._TB_CLI_CTT_CONTACTOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_TCT_TIPO_CONTACTO = this;
		}
		
		private void detach_TB_CLI_CTT_CONTACTOS(TB_CLI_CTT_CONTACTOS entity)
		{
			this.SendPropertyChanging();
			entity.TB_CLI_TCT_TIPO_CONTACTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_CLI_SUC_SUCURSAL")]
	public partial class TB_CLI_SUC_SUCURSAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_CLI_SUC_ID;
		
		private int _PK_CLI_EMP_RUT;
		
		private int _PK_CLI_DIR_ID;
		
		private string _FL_CLI_SUC_NOMBRE;
		
		private EntityRef<TB_CLI_DIR_DIRECCIONES> _TB_CLI_DIR_DIRECCIONES;
		
		private EntityRef<TB_CLI_EMP_EMPRESAS> _TB_CLI_EMP_EMPRESAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CLI_SUC_IDChanging(int value);
    partial void OnPK_CLI_SUC_IDChanged();
    partial void OnPK_CLI_EMP_RUTChanging(int value);
    partial void OnPK_CLI_EMP_RUTChanged();
    partial void OnPK_CLI_DIR_IDChanging(int value);
    partial void OnPK_CLI_DIR_IDChanged();
    partial void OnFL_CLI_SUC_NOMBREChanging(string value);
    partial void OnFL_CLI_SUC_NOMBREChanged();
    #endregion
		
		public TB_CLI_SUC_SUCURSAL()
		{
			this._TB_CLI_DIR_DIRECCIONES = default(EntityRef<TB_CLI_DIR_DIRECCIONES>);
			this._TB_CLI_EMP_EMPRESAS = default(EntityRef<TB_CLI_EMP_EMPRESAS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_SUC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_CLI_SUC_ID
		{
			get
			{
				return this._PK_CLI_SUC_ID;
			}
			set
			{
				if ((this._PK_CLI_SUC_ID != value))
				{
					this.OnPK_CLI_SUC_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_SUC_ID = value;
					this.SendPropertyChanged("PK_CLI_SUC_ID");
					this.OnPK_CLI_SUC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_EMP_RUT", DbType="Int NOT NULL")]
		public int PK_CLI_EMP_RUT
		{
			get
			{
				return this._PK_CLI_EMP_RUT;
			}
			set
			{
				if ((this._PK_CLI_EMP_RUT != value))
				{
					if (this._TB_CLI_EMP_EMPRESAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_EMP_RUTChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_EMP_RUT = value;
					this.SendPropertyChanged("PK_CLI_EMP_RUT");
					this.OnPK_CLI_EMP_RUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_CLI_DIR_ID", DbType="Int NOT NULL")]
		public int PK_CLI_DIR_ID
		{
			get
			{
				return this._PK_CLI_DIR_ID;
			}
			set
			{
				if ((this._PK_CLI_DIR_ID != value))
				{
					if (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPK_CLI_DIR_IDChanging(value);
					this.SendPropertyChanging();
					this._PK_CLI_DIR_ID = value;
					this.SendPropertyChanged("PK_CLI_DIR_ID");
					this.OnPK_CLI_DIR_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CLI_SUC_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FL_CLI_SUC_NOMBRE
		{
			get
			{
				return this._FL_CLI_SUC_NOMBRE;
			}
			set
			{
				if ((this._FL_CLI_SUC_NOMBRE != value))
				{
					this.OnFL_CLI_SUC_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._FL_CLI_SUC_NOMBRE = value;
					this.SendPropertyChanged("FL_CLI_SUC_NOMBRE");
					this.OnFL_CLI_SUC_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_DIR_DIRECCIONES_TB_CLI_SUC_SUCURSAL", Storage="_TB_CLI_DIR_DIRECCIONES", ThisKey="PK_CLI_DIR_ID", OtherKey="PK_CLI_DIR_ID", IsForeignKey=true)]
		public TB_CLI_DIR_DIRECCIONES TB_CLI_DIR_DIRECCIONES
		{
			get
			{
				return this._TB_CLI_DIR_DIRECCIONES.Entity;
			}
			set
			{
				TB_CLI_DIR_DIRECCIONES previousValue = this._TB_CLI_DIR_DIRECCIONES.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_DIR_DIRECCIONES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_DIR_DIRECCIONES.Entity = null;
						previousValue.TB_CLI_SUC_SUCURSAL.Remove(this);
					}
					this._TB_CLI_DIR_DIRECCIONES.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_SUC_SUCURSAL.Add(this);
						this._PK_CLI_DIR_ID = value.PK_CLI_DIR_ID;
					}
					else
					{
						this._PK_CLI_DIR_ID = default(int);
					}
					this.SendPropertyChanged("TB_CLI_DIR_DIRECCIONES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_CLI_EMP_EMPRESAS_TB_CLI_SUC_SUCURSAL", Storage="_TB_CLI_EMP_EMPRESAS", ThisKey="PK_CLI_EMP_RUT", OtherKey="PK_CLI_EMP_RUT", IsForeignKey=true)]
		public TB_CLI_EMP_EMPRESAS TB_CLI_EMP_EMPRESAS
		{
			get
			{
				return this._TB_CLI_EMP_EMPRESAS.Entity;
			}
			set
			{
				TB_CLI_EMP_EMPRESAS previousValue = this._TB_CLI_EMP_EMPRESAS.Entity;
				if (((previousValue != value) 
							|| (this._TB_CLI_EMP_EMPRESAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_CLI_EMP_EMPRESAS.Entity = null;
						previousValue.TB_CLI_SUC_SUCURSAL.Remove(this);
					}
					this._TB_CLI_EMP_EMPRESAS.Entity = value;
					if ((value != null))
					{
						value.TB_CLI_SUC_SUCURSAL.Add(this);
						this._PK_CLI_EMP_RUT = value.PK_CLI_EMP_RUT;
					}
					else
					{
						this._PK_CLI_EMP_RUT = default(int);
					}
					this.SendPropertyChanged("TB_CLI_EMP_EMPRESAS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
