//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.wsFolcourier {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="folweb", ConfigurationName="wsFolcourier.wsFolCourierSoap")]
    public interface wsFolCourierSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmManifiestoRutaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.PR_FOL_MRC_MANIFIESTO_RUTA_CLIENTE_MOVILResult[] wmManifiestoRutaCliente(decimal MAN_ID, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmESE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.TB_FOL_ESE_ESTADO_ENTREGA[] wmESE(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmOES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoFOL_OES[] wmOES(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmEST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoFOL_EST[] wmEST(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmConexion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoConexion wmConexion(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmGuardaEntrega", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoGuardar wmGuardaEntrega(string Token, decimal OTP, decimal OTD, int EST_ID, int OES_ID, string ENT_RUT, string ENT_RECIBE, int USU_RUT, System.DateTime Fecha, Courier.wsFolcourier.DatosAdjuntos[] oAdjuntos, string Latitud, string Longitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmLoginUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoLogin wmLoginUsuario(string Token, string Rut, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmValidarManifiesto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoGuardar wmValidarManifiesto(string Token, decimal IdMan);
        
        // CODEGEN: El parámetro 'oFoto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmGuardaFoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.wmGuardaFotoResponse wmGuardaFoto(Courier.wsFolcourier.wmGuardaFotoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmFechaActual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.fecha wmFechaActual();
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmCreaOT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.clsRetorno wmCreaOT(Courier.wsFolcourier.clsEntrada oDatosOT);
        
        [System.ServiceModel.OperationContractAttribute(Action="folweb/wmLoginUsuarioEA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Courier.wsFolcourier.RetornoLoginEA wmLoginUsuarioEA(string Token, string Rut, string Password);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class PR_FOL_MRC_MANIFIESTO_RUTA_CLIENTE_MOVILResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string otField;
        
        private string fL_FOL_OTD_REFERENCIA1Field;
        
        private string fECHAField;
        
        private string sER_NOMBREField;
        
        private string fL_FOL_OTD_DESTINATARIO_NOMBREField;
        
        private System.Nullable<int> bULTOSField;
        
        private System.Nullable<double> pESO_FISICOField;
        
        private string fL_FOL_OTD_TELEFONOField;
        
        private string fL_FOL_OTD_DESTINATARIO_DIRECCIONField;
        
        private string fL_FOL_OTD_DESTINATARIO_NUMEROField;
        
        private string cOMUNAField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OT {
            get {
                return this.otField;
            }
            set {
                this.otField = value;
                this.RaisePropertyChanged("OT");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FL_FOL_OTD_REFERENCIA1 {
            get {
                return this.fL_FOL_OTD_REFERENCIA1Field;
            }
            set {
                this.fL_FOL_OTD_REFERENCIA1Field = value;
                this.RaisePropertyChanged("FL_FOL_OTD_REFERENCIA1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
                this.RaisePropertyChanged("FECHA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SER_NOMBRE {
            get {
                return this.sER_NOMBREField;
            }
            set {
                this.sER_NOMBREField = value;
                this.RaisePropertyChanged("SER_NOMBRE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FL_FOL_OTD_DESTINATARIO_NOMBRE {
            get {
                return this.fL_FOL_OTD_DESTINATARIO_NOMBREField;
            }
            set {
                this.fL_FOL_OTD_DESTINATARIO_NOMBREField = value;
                this.RaisePropertyChanged("FL_FOL_OTD_DESTINATARIO_NOMBRE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> BULTOS {
            get {
                return this.bULTOSField;
            }
            set {
                this.bULTOSField = value;
                this.RaisePropertyChanged("BULTOS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<double> PESO_FISICO {
            get {
                return this.pESO_FISICOField;
            }
            set {
                this.pESO_FISICOField = value;
                this.RaisePropertyChanged("PESO_FISICO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FL_FOL_OTD_TELEFONO {
            get {
                return this.fL_FOL_OTD_TELEFONOField;
            }
            set {
                this.fL_FOL_OTD_TELEFONOField = value;
                this.RaisePropertyChanged("FL_FOL_OTD_TELEFONO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FL_FOL_OTD_DESTINATARIO_DIRECCION {
            get {
                return this.fL_FOL_OTD_DESTINATARIO_DIRECCIONField;
            }
            set {
                this.fL_FOL_OTD_DESTINATARIO_DIRECCIONField = value;
                this.RaisePropertyChanged("FL_FOL_OTD_DESTINATARIO_DIRECCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FL_FOL_OTD_DESTINATARIO_NUMERO {
            get {
                return this.fL_FOL_OTD_DESTINATARIO_NUMEROField;
            }
            set {
                this.fL_FOL_OTD_DESTINATARIO_NUMEROField = value;
                this.RaisePropertyChanged("FL_FOL_OTD_DESTINATARIO_NUMERO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string COMUNA {
            get {
                return this.cOMUNAField;
            }
            set {
                this.cOMUNAField = value;
                this.RaisePropertyChanged("COMUNA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoDatosSucursal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private string mensajeField;
        
        private int sucursalField;
        
        private int estadoFinalOTField;
        
        private int empresaField;
        
        private int servicioField;
        
        private string nombreServicioField;
        
        private string nombreImpresoraField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int EstadoFinalOT {
            get {
                return this.estadoFinalOTField;
            }
            set {
                this.estadoFinalOTField = value;
                this.RaisePropertyChanged("EstadoFinalOT");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
                this.RaisePropertyChanged("Empresa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("Servicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NombreServicio {
            get {
                return this.nombreServicioField;
            }
            set {
                this.nombreServicioField = value;
                this.RaisePropertyChanged("NombreServicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NombreImpresora {
            get {
                return this.nombreImpresoraField;
            }
            set {
                this.nombreImpresoraField = value;
                this.RaisePropertyChanged("NombreImpresora");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoLoginEA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private string mensajeField;
        
        private RetornoDatosSucursal[] oDatosSucursalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public RetornoDatosSucursal[] oDatosSucursal {
            get {
                return this.oDatosSucursalField;
            }
            set {
                this.oDatosSucursalField = value;
                this.RaisePropertyChanged("oDatosSucursal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class clsRetorno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool exitosoField;
        
        private int idErrorField;
        
        private string mensajeErrorField;
        
        private bool conOTField;
        
        private decimal oTPField;
        
        private decimal oTDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Exitoso {
            get {
                return this.exitosoField;
            }
            set {
                this.exitosoField = value;
                this.RaisePropertyChanged("Exitoso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdError {
            get {
                return this.idErrorField;
            }
            set {
                this.idErrorField = value;
                this.RaisePropertyChanged("IdError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ConOT {
            get {
                return this.conOTField;
            }
            set {
                this.conOTField = value;
                this.RaisePropertyChanged("ConOT");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal OTP {
            get {
                return this.oTPField;
            }
            set {
                this.oTPField = value;
                this.RaisePropertyChanged("OTP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal OTD {
            get {
                return this.oTDField;
            }
            set {
                this.oTDField = value;
                this.RaisePropertyChanged("OTD");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class InformacionAdicional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int cantidadField;
        
        private string codigoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class DocumentosAsociados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipoDocumentoField;
        
        private decimal numeroDocumentoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("TipoDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("NumeroDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class clsEntrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rutUsuarioField;
        
        private int estadoOTField;
        
        private string rutField;
        
        private string nombreField;
        
        private string fonoField;
        
        private string direccionField;
        
        private string comunaField;
        
        private float pesoField;
        
        private float pesoVolumetricoField;
        
        private int cantidadBultosField;
        
        private decimal referencia1Field;
        
        private string observacion1Field;
        
        private string observacion2Field;
        
        private int rutEmpresaField;
        
        private int servicioField;
        
        private int sucursalField;
        
        private DocumentosAsociados[] listaDocumentosField;
        
        private InformacionAdicional[] listaInformacionAdicionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RutUsuario {
            get {
                return this.rutUsuarioField;
            }
            set {
                this.rutUsuarioField = value;
                this.RaisePropertyChanged("RutUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int EstadoOT {
            get {
                return this.estadoOTField;
            }
            set {
                this.estadoOTField = value;
                this.RaisePropertyChanged("EstadoOT");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Fono {
            get {
                return this.fonoField;
            }
            set {
                this.fonoField = value;
                this.RaisePropertyChanged("Fono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("Comuna");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("Peso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float PesoVolumetrico {
            get {
                return this.pesoVolumetricoField;
            }
            set {
                this.pesoVolumetricoField = value;
                this.RaisePropertyChanged("PesoVolumetrico");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CantidadBultos {
            get {
                return this.cantidadBultosField;
            }
            set {
                this.cantidadBultosField = value;
                this.RaisePropertyChanged("CantidadBultos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Referencia1 {
            get {
                return this.referencia1Field;
            }
            set {
                this.referencia1Field = value;
                this.RaisePropertyChanged("Referencia1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Observacion1 {
            get {
                return this.observacion1Field;
            }
            set {
                this.observacion1Field = value;
                this.RaisePropertyChanged("Observacion1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Observacion2 {
            get {
                return this.observacion2Field;
            }
            set {
                this.observacion2Field = value;
                this.RaisePropertyChanged("Observacion2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int RutEmpresa {
            get {
                return this.rutEmpresaField;
            }
            set {
                this.rutEmpresaField = value;
                this.RaisePropertyChanged("RutEmpresa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
                this.RaisePropertyChanged("Servicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public DocumentosAsociados[] ListaDocumentos {
            get {
                return this.listaDocumentosField;
            }
            set {
                this.listaDocumentosField = value;
                this.RaisePropertyChanged("ListaDocumentos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public InformacionAdicional[] ListaInformacionAdicional {
            get {
                return this.listaInformacionAdicionalField;
            }
            set {
                this.listaInformacionAdicionalField = value;
                this.RaisePropertyChanged("ListaInformacionAdicional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class fecha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string yearField;
        
        private string mesField;
        
        private string diaField;
        
        private string horaField;
        
        private string minutosField;
        
        private string segundosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("mes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("hora");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string minutos {
            get {
                return this.minutosField;
            }
            set {
                this.minutosField = value;
                this.RaisePropertyChanged("minutos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string segundos {
            get {
                return this.segundosField;
            }
            set {
                this.segundosField = value;
                this.RaisePropertyChanged("segundos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoGuardar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class DatosAdjuntos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] archivoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("Archivo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoConexion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoFOL_EST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pK_FOL_EST_IDField;
        
        private string fL_FOL_EST_NOMBREField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PK_FOL_EST_ID {
            get {
                return this.pK_FOL_EST_IDField;
            }
            set {
                this.pK_FOL_EST_IDField = value;
                this.RaisePropertyChanged("PK_FOL_EST_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FL_FOL_EST_NOMBRE {
            get {
                return this.fL_FOL_EST_NOMBREField;
            }
            set {
                this.fL_FOL_EST_NOMBREField = value;
                this.RaisePropertyChanged("FL_FOL_EST_NOMBRE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class RetornoFOL_OES : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pK_FOL_OES_IDField;
        
        private int pK_FOL_EST_IDField;
        
        private string fL_FOL_OES_NOMBREField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PK_FOL_OES_ID {
            get {
                return this.pK_FOL_OES_IDField;
            }
            set {
                this.pK_FOL_OES_IDField = value;
                this.RaisePropertyChanged("PK_FOL_OES_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PK_FOL_EST_ID {
            get {
                return this.pK_FOL_EST_IDField;
            }
            set {
                this.pK_FOL_EST_IDField = value;
                this.RaisePropertyChanged("PK_FOL_EST_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FL_FOL_OES_NOMBRE {
            get {
                return this.fL_FOL_OES_NOMBREField;
            }
            set {
                this.fL_FOL_OES_NOMBREField = value;
                this.RaisePropertyChanged("FL_FOL_OES_NOMBRE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="folweb")]
    public partial class TB_FOL_ESE_ESTADO_ENTREGA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pK_FOL_EST_IDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PK_FOL_EST_ID {
            get {
                return this.pK_FOL_EST_IDField;
            }
            set {
                this.pK_FOL_EST_IDField = value;
                this.RaisePropertyChanged("PK_FOL_EST_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmGuardaFoto", WrapperNamespace="folweb", IsWrapped=true)]
    public partial class wmGuardaFotoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="folweb", Order=0)]
        public decimal OTP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="folweb", Order=1)]
        public decimal OTD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="folweb", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] oFoto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="folweb", Order=3)]
        public string Nombre;
        
        public wmGuardaFotoRequest() {
        }
        
        public wmGuardaFotoRequest(decimal OTP, decimal OTD, byte[] oFoto, string Nombre) {
            this.OTP = OTP;
            this.OTD = OTD;
            this.oFoto = oFoto;
            this.Nombre = Nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wmGuardaFotoResponse", WrapperNamespace="folweb", IsWrapped=true)]
    public partial class wmGuardaFotoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="folweb", Order=0)]
        public Courier.wsFolcourier.RetornoGuardar wmGuardaFotoResult;
        
        public wmGuardaFotoResponse() {
        }
        
        public wmGuardaFotoResponse(Courier.wsFolcourier.RetornoGuardar wmGuardaFotoResult) {
            this.wmGuardaFotoResult = wmGuardaFotoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsFolCourierSoapChannel : Courier.wsFolcourier.wsFolCourierSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsFolCourierSoapClient : System.ServiceModel.ClientBase<Courier.wsFolcourier.wsFolCourierSoap>, Courier.wsFolcourier.wsFolCourierSoap {
        
        public wsFolCourierSoapClient() {
        }
        
        public wsFolCourierSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsFolCourierSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFolCourierSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFolCourierSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Courier.wsFolcourier.PR_FOL_MRC_MANIFIESTO_RUTA_CLIENTE_MOVILResult[] wmManifiestoRutaCliente(decimal MAN_ID, string Token) {
            return base.Channel.wmManifiestoRutaCliente(MAN_ID, Token);
        }
        
        public Courier.wsFolcourier.TB_FOL_ESE_ESTADO_ENTREGA[] wmESE(string Token) {
            return base.Channel.wmESE(Token);
        }
        
        public Courier.wsFolcourier.RetornoFOL_OES[] wmOES(string Token) {
            return base.Channel.wmOES(Token);
        }
        
        public Courier.wsFolcourier.RetornoFOL_EST[] wmEST(string Token) {
            return base.Channel.wmEST(Token);
        }
        
        public Courier.wsFolcourier.RetornoConexion wmConexion(string Token) {
            return base.Channel.wmConexion(Token);
        }
        
        public Courier.wsFolcourier.RetornoGuardar wmGuardaEntrega(string Token, decimal OTP, decimal OTD, int EST_ID, int OES_ID, string ENT_RUT, string ENT_RECIBE, int USU_RUT, System.DateTime Fecha, Courier.wsFolcourier.DatosAdjuntos[] oAdjuntos, string Latitud, string Longitud) {
            return base.Channel.wmGuardaEntrega(Token, OTP, OTD, EST_ID, OES_ID, ENT_RUT, ENT_RECIBE, USU_RUT, Fecha, oAdjuntos, Latitud, Longitud);
        }
        
        public Courier.wsFolcourier.RetornoLogin wmLoginUsuario(string Token, string Rut, string Password) {
            return base.Channel.wmLoginUsuario(Token, Rut, Password);
        }
        
        public Courier.wsFolcourier.RetornoGuardar wmValidarManifiesto(string Token, decimal IdMan) {
            return base.Channel.wmValidarManifiesto(Token, IdMan);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Courier.wsFolcourier.wmGuardaFotoResponse Courier.wsFolcourier.wsFolCourierSoap.wmGuardaFoto(Courier.wsFolcourier.wmGuardaFotoRequest request) {
            return base.Channel.wmGuardaFoto(request);
        }
        
        public Courier.wsFolcourier.RetornoGuardar wmGuardaFoto(decimal OTP, decimal OTD, byte[] oFoto, string Nombre) {
            Courier.wsFolcourier.wmGuardaFotoRequest inValue = new Courier.wsFolcourier.wmGuardaFotoRequest();
            inValue.OTP = OTP;
            inValue.OTD = OTD;
            inValue.oFoto = oFoto;
            inValue.Nombre = Nombre;
            Courier.wsFolcourier.wmGuardaFotoResponse retVal = ((Courier.wsFolcourier.wsFolCourierSoap)(this)).wmGuardaFoto(inValue);
            return retVal.wmGuardaFotoResult;
        }
        
        public Courier.wsFolcourier.fecha wmFechaActual() {
            return base.Channel.wmFechaActual();
        }
        
        public Courier.wsFolcourier.clsRetorno wmCreaOT(Courier.wsFolcourier.clsEntrada oDatosOT) {
            return base.Channel.wmCreaOT(oDatosOT);
        }
        
        public Courier.wsFolcourier.RetornoLoginEA wmLoginUsuarioEA(string Token, string Rut, string Password) {
            return base.Channel.wmLoginUsuarioEA(Token, Rut, Password);
        }
    }
}
