//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace SilverlightApp.ReferenciaServicioWeb {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioSilverlight.wsEncabezado", Namespace="http://schemas.datacontract.org/2004/07/Courier.WebService")]
    public partial class ServicioSilverlightwsEncabezado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal CantidadBultosField;
        
        private string ClienteField;
        
        private string ComunaField;
        
        private string DireccionField;
        
        private System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsDetalleNormal> ListaDetalleField;
        
        private string LocalidadField;
        
        private decimal OTDField;
        
        private decimal OTPField;
        
        private decimal PalletField;
        
        private string Referencia1Field;
        
        private string Referencia2Field;
        
        private string ServicioField;
        
        private string SucursalDestinoField;
        
        private string TelefonoField;
        
        private string ViaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CantidadBultos {
            get {
                return this.CantidadBultosField;
            }
            set {
                if ((this.CantidadBultosField.Equals(value) != true)) {
                    this.CantidadBultosField = value;
                    this.RaisePropertyChanged("CantidadBultos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comuna {
            get {
                return this.ComunaField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunaField, value) != true)) {
                    this.ComunaField = value;
                    this.RaisePropertyChanged("Comuna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsDetalleNormal> ListaDetalle {
            get {
                return this.ListaDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDetalleField, value) != true)) {
                    this.ListaDetalleField = value;
                    this.RaisePropertyChanged("ListaDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OTD {
            get {
                return this.OTDField;
            }
            set {
                if ((this.OTDField.Equals(value) != true)) {
                    this.OTDField = value;
                    this.RaisePropertyChanged("OTD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OTP {
            get {
                return this.OTPField;
            }
            set {
                if ((this.OTPField.Equals(value) != true)) {
                    this.OTPField = value;
                    this.RaisePropertyChanged("OTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pallet {
            get {
                return this.PalletField;
            }
            set {
                if ((this.PalletField.Equals(value) != true)) {
                    this.PalletField = value;
                    this.RaisePropertyChanged("Pallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia1 {
            get {
                return this.Referencia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Referencia1Field, value) != true)) {
                    this.Referencia1Field = value;
                    this.RaisePropertyChanged("Referencia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia2 {
            get {
                return this.Referencia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Referencia2Field, value) != true)) {
                    this.Referencia2Field = value;
                    this.RaisePropertyChanged("Referencia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio {
            get {
                return this.ServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicioField, value) != true)) {
                    this.ServicioField = value;
                    this.RaisePropertyChanged("Servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalDestino {
            get {
                return this.SucursalDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalDestinoField, value) != true)) {
                    this.SucursalDestinoField = value;
                    this.RaisePropertyChanged("SucursalDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Via {
            get {
                return this.ViaField;
            }
            set {
                if ((object.ReferenceEquals(this.ViaField, value) != true)) {
                    this.ViaField = value;
                    this.RaisePropertyChanged("Via");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioSilverlight.wsDetalleNormal", Namespace="http://schemas.datacontract.org/2004/07/Courier.WebService")]
    public partial class ServicioSilverlightwsDetalleNormal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int NumeroBultoField;
        
        private System.Nullable<float> PesoField;
        
        private int TipoEtiquetaField;
        
        private decimal idBultoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroBulto {
            get {
                return this.NumeroBultoField;
            }
            set {
                if ((this.NumeroBultoField.Equals(value) != true)) {
                    this.NumeroBultoField = value;
                    this.RaisePropertyChanged("NumeroBulto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoEtiqueta {
            get {
                return this.TipoEtiquetaField;
            }
            set {
                if ((this.TipoEtiquetaField.Equals(value) != true)) {
                    this.TipoEtiquetaField = value;
                    this.RaisePropertyChanged("TipoEtiqueta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal idBulto {
            get {
                return this.idBultoField;
            }
            set {
                if ((this.idBultoField.Equals(value) != true)) {
                    this.idBultoField = value;
                    this.RaisePropertyChanged("idBulto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioSilverlight.classImpresionGuia", Namespace="http://schemas.datacontract.org/2004/07/Courier.WebService")]
    public partial class ServicioSilverlightclassImpresionGuia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal OTDField;
        
        private decimal OTPField;
        
        private string Referencia1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OTD {
            get {
                return this.OTDField;
            }
            set {
                if ((this.OTDField.Equals(value) != true)) {
                    this.OTDField = value;
                    this.RaisePropertyChanged("OTD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OTP {
            get {
                return this.OTPField;
            }
            set {
                if ((this.OTPField.Equals(value) != true)) {
                    this.OTPField = value;
                    this.RaisePropertyChanged("OTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia1 {
            get {
                return this.Referencia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Referencia1Field, value) != true)) {
                    this.Referencia1Field = value;
                    this.RaisePropertyChanged("Referencia1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ReferenciaServicioWeb.ServicioSilverlight")]
    public interface ServicioSilverlight {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/DoWork", ReplyAction="urn:ServicioSilverlight/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        string EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/ModificarImpresora", ReplyAction="urn:ServicioSilverlight/ModificarImpresoraResponse")]
        System.IAsyncResult BeginModificarImpresora(string oNombreImpresora, int oRut, System.AsyncCallback callback, object asyncState);
        
        bool EndModificarImpresora(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/ImpresionEtiqueta", ReplyAction="urn:ServicioSilverlight/ImpresionEtiquetaResponse")]
        System.IAsyncResult BeginImpresionEtiqueta(decimal OTP, decimal OTD, System.AsyncCallback callback, object asyncState);
        
        SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado EndImpresionEtiqueta(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/ImpresionEtiquetaPallet", ReplyAction="urn:ServicioSilverlight/ImpresionEtiquetaPalletResponse")]
        System.IAsyncResult BeginImpresionEtiquetaPallet(decimal OTP, decimal OTD, int NPALLET, int BLTOS, System.AsyncCallback callback, object asyncState);
        
        SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado EndImpresionEtiquetaPallet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/ImpresionEtiquetaPorOTP", ReplyAction="urn:ServicioSilverlight/ImpresionEtiquetaPorOTPResponse")]
        System.IAsyncResult BeginImpresionEtiquetaPorOTP(decimal OTP, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado> EndImpresionEtiquetaPorOTP(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/ImpresionGuiaMasiva", ReplyAction="urn:ServicioSilverlight/ImpresionGuiaMasivaResponse")]
        System.IAsyncResult BeginImpresionGuiaMasiva(decimal OTP, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia> EndImpresionGuiaMasiva(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ServicioSilverlight/ImpresionCustom", ReplyAction="urn:ServicioSilverlight/ImpresionCustomResponse")]
        System.IAsyncResult BeginImpresionCustom(decimal OTP, decimal OTD, int Cantidad, int TipoEtiqueta, decimal Bulto1, decimal Bulto2, decimal Bulto3, decimal Bulto4, System.AsyncCallback callback, object asyncState);
        
        SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado EndImpresionCustom(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSilverlightChannel : SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoWorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DoWorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificarImpresoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ModificarImpresoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpresionEtiquetaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ImpresionEtiquetaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpresionEtiquetaPalletCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ImpresionEtiquetaPalletCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpresionEtiquetaPorOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ImpresionEtiquetaPorOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpresionGuiaMasivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ImpresionGuiaMasivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpresionCustomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ImpresionCustomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSilverlightClient : System.ServiceModel.ClientBase<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight>, SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarImpresoraDelegate;
        
        private EndOperationDelegate onEndModificarImpresoraDelegate;
        
        private System.Threading.SendOrPostCallback onModificarImpresoraCompletedDelegate;
        
        private BeginOperationDelegate onBeginImpresionEtiquetaDelegate;
        
        private EndOperationDelegate onEndImpresionEtiquetaDelegate;
        
        private System.Threading.SendOrPostCallback onImpresionEtiquetaCompletedDelegate;
        
        private BeginOperationDelegate onBeginImpresionEtiquetaPalletDelegate;
        
        private EndOperationDelegate onEndImpresionEtiquetaPalletDelegate;
        
        private System.Threading.SendOrPostCallback onImpresionEtiquetaPalletCompletedDelegate;
        
        private BeginOperationDelegate onBeginImpresionEtiquetaPorOTPDelegate;
        
        private EndOperationDelegate onEndImpresionEtiquetaPorOTPDelegate;
        
        private System.Threading.SendOrPostCallback onImpresionEtiquetaPorOTPCompletedDelegate;
        
        private BeginOperationDelegate onBeginImpresionGuiaMasivaDelegate;
        
        private EndOperationDelegate onEndImpresionGuiaMasivaDelegate;
        
        private System.Threading.SendOrPostCallback onImpresionGuiaMasivaCompletedDelegate;
        
        private BeginOperationDelegate onBeginImpresionCustomDelegate;
        
        private EndOperationDelegate onEndImpresionCustomDelegate;
        
        private System.Threading.SendOrPostCallback onImpresionCustomCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServicioSilverlightClient() {
        }
        
        public ServicioSilverlightClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSilverlightClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSilverlightClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSilverlightClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<DoWorkCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<ModificarImpresoraCompletedEventArgs> ModificarImpresoraCompleted;
        
        public event System.EventHandler<ImpresionEtiquetaCompletedEventArgs> ImpresionEtiquetaCompleted;
        
        public event System.EventHandler<ImpresionEtiquetaPalletCompletedEventArgs> ImpresionEtiquetaPalletCompleted;
        
        public event System.EventHandler<ImpresionEtiquetaPorOTPCompletedEventArgs> ImpresionEtiquetaPorOTPCompleted;
        
        public event System.EventHandler<ImpresionGuiaMasivaCompletedEventArgs> ImpresionGuiaMasivaCompleted;
        
        public event System.EventHandler<ImpresionCustomCompletedEventArgs> ImpresionCustomCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndDoWork(System.IAsyncResult result) {
            return base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            string retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndDoWork(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new DoWorkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginModificarImpresora(string oNombreImpresora, int oRut, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarImpresora(oNombreImpresora, oRut, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndModificarImpresora(System.IAsyncResult result) {
            return base.Channel.EndModificarImpresora(result);
        }
        
        private System.IAsyncResult OnBeginModificarImpresora(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string oNombreImpresora = ((string)(inValues[0]));
            int oRut = ((int)(inValues[1]));
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginModificarImpresora(oNombreImpresora, oRut, callback, asyncState);
        }
        
        private object[] OnEndModificarImpresora(System.IAsyncResult result) {
            bool retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndModificarImpresora(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificarImpresoraCompleted(object state) {
            if ((this.ModificarImpresoraCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarImpresoraCompleted(this, new ModificarImpresoraCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarImpresoraAsync(string oNombreImpresora, int oRut) {
            this.ModificarImpresoraAsync(oNombreImpresora, oRut, null);
        }
        
        public void ModificarImpresoraAsync(string oNombreImpresora, int oRut, object userState) {
            if ((this.onBeginModificarImpresoraDelegate == null)) {
                this.onBeginModificarImpresoraDelegate = new BeginOperationDelegate(this.OnBeginModificarImpresora);
            }
            if ((this.onEndModificarImpresoraDelegate == null)) {
                this.onEndModificarImpresoraDelegate = new EndOperationDelegate(this.OnEndModificarImpresora);
            }
            if ((this.onModificarImpresoraCompletedDelegate == null)) {
                this.onModificarImpresoraCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarImpresoraCompleted);
            }
            base.InvokeAsync(this.onBeginModificarImpresoraDelegate, new object[] {
                        oNombreImpresora,
                        oRut}, this.onEndModificarImpresoraDelegate, this.onModificarImpresoraCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginImpresionEtiqueta(decimal OTP, decimal OTD, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImpresionEtiqueta(OTP, OTD, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndImpresionEtiqueta(System.IAsyncResult result) {
            return base.Channel.EndImpresionEtiqueta(result);
        }
        
        private System.IAsyncResult OnBeginImpresionEtiqueta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            decimal OTP = ((decimal)(inValues[0]));
            decimal OTD = ((decimal)(inValues[1]));
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginImpresionEtiqueta(OTP, OTD, callback, asyncState);
        }
        
        private object[] OnEndImpresionEtiqueta(System.IAsyncResult result) {
            SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndImpresionEtiqueta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnImpresionEtiquetaCompleted(object state) {
            if ((this.ImpresionEtiquetaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImpresionEtiquetaCompleted(this, new ImpresionEtiquetaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImpresionEtiquetaAsync(decimal OTP, decimal OTD) {
            this.ImpresionEtiquetaAsync(OTP, OTD, null);
        }
        
        public void ImpresionEtiquetaAsync(decimal OTP, decimal OTD, object userState) {
            if ((this.onBeginImpresionEtiquetaDelegate == null)) {
                this.onBeginImpresionEtiquetaDelegate = new BeginOperationDelegate(this.OnBeginImpresionEtiqueta);
            }
            if ((this.onEndImpresionEtiquetaDelegate == null)) {
                this.onEndImpresionEtiquetaDelegate = new EndOperationDelegate(this.OnEndImpresionEtiqueta);
            }
            if ((this.onImpresionEtiquetaCompletedDelegate == null)) {
                this.onImpresionEtiquetaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImpresionEtiquetaCompleted);
            }
            base.InvokeAsync(this.onBeginImpresionEtiquetaDelegate, new object[] {
                        OTP,
                        OTD}, this.onEndImpresionEtiquetaDelegate, this.onImpresionEtiquetaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginImpresionEtiquetaPallet(decimal OTP, decimal OTD, int NPALLET, int BLTOS, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImpresionEtiquetaPallet(OTP, OTD, NPALLET, BLTOS, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndImpresionEtiquetaPallet(System.IAsyncResult result) {
            return base.Channel.EndImpresionEtiquetaPallet(result);
        }
        
        private System.IAsyncResult OnBeginImpresionEtiquetaPallet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            decimal OTP = ((decimal)(inValues[0]));
            decimal OTD = ((decimal)(inValues[1]));
            int NPALLET = ((int)(inValues[2]));
            int BLTOS = ((int)(inValues[3]));
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginImpresionEtiquetaPallet(OTP, OTD, NPALLET, BLTOS, callback, asyncState);
        }
        
        private object[] OnEndImpresionEtiquetaPallet(System.IAsyncResult result) {
            SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndImpresionEtiquetaPallet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnImpresionEtiquetaPalletCompleted(object state) {
            if ((this.ImpresionEtiquetaPalletCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImpresionEtiquetaPalletCompleted(this, new ImpresionEtiquetaPalletCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImpresionEtiquetaPalletAsync(decimal OTP, decimal OTD, int NPALLET, int BLTOS) {
            this.ImpresionEtiquetaPalletAsync(OTP, OTD, NPALLET, BLTOS, null);
        }
        
        public void ImpresionEtiquetaPalletAsync(decimal OTP, decimal OTD, int NPALLET, int BLTOS, object userState) {
            if ((this.onBeginImpresionEtiquetaPalletDelegate == null)) {
                this.onBeginImpresionEtiquetaPalletDelegate = new BeginOperationDelegate(this.OnBeginImpresionEtiquetaPallet);
            }
            if ((this.onEndImpresionEtiquetaPalletDelegate == null)) {
                this.onEndImpresionEtiquetaPalletDelegate = new EndOperationDelegate(this.OnEndImpresionEtiquetaPallet);
            }
            if ((this.onImpresionEtiquetaPalletCompletedDelegate == null)) {
                this.onImpresionEtiquetaPalletCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImpresionEtiquetaPalletCompleted);
            }
            base.InvokeAsync(this.onBeginImpresionEtiquetaPalletDelegate, new object[] {
                        OTP,
                        OTD,
                        NPALLET,
                        BLTOS}, this.onEndImpresionEtiquetaPalletDelegate, this.onImpresionEtiquetaPalletCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginImpresionEtiquetaPorOTP(decimal OTP, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImpresionEtiquetaPorOTP(OTP, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado> SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndImpresionEtiquetaPorOTP(System.IAsyncResult result) {
            return base.Channel.EndImpresionEtiquetaPorOTP(result);
        }
        
        private System.IAsyncResult OnBeginImpresionEtiquetaPorOTP(object[] inValues, System.AsyncCallback callback, object asyncState) {
            decimal OTP = ((decimal)(inValues[0]));
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginImpresionEtiquetaPorOTP(OTP, callback, asyncState);
        }
        
        private object[] OnEndImpresionEtiquetaPorOTP(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado> retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndImpresionEtiquetaPorOTP(result);
            return new object[] {
                    retVal};
        }
        
        private void OnImpresionEtiquetaPorOTPCompleted(object state) {
            if ((this.ImpresionEtiquetaPorOTPCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImpresionEtiquetaPorOTPCompleted(this, new ImpresionEtiquetaPorOTPCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImpresionEtiquetaPorOTPAsync(decimal OTP) {
            this.ImpresionEtiquetaPorOTPAsync(OTP, null);
        }
        
        public void ImpresionEtiquetaPorOTPAsync(decimal OTP, object userState) {
            if ((this.onBeginImpresionEtiquetaPorOTPDelegate == null)) {
                this.onBeginImpresionEtiquetaPorOTPDelegate = new BeginOperationDelegate(this.OnBeginImpresionEtiquetaPorOTP);
            }
            if ((this.onEndImpresionEtiquetaPorOTPDelegate == null)) {
                this.onEndImpresionEtiquetaPorOTPDelegate = new EndOperationDelegate(this.OnEndImpresionEtiquetaPorOTP);
            }
            if ((this.onImpresionEtiquetaPorOTPCompletedDelegate == null)) {
                this.onImpresionEtiquetaPorOTPCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImpresionEtiquetaPorOTPCompleted);
            }
            base.InvokeAsync(this.onBeginImpresionEtiquetaPorOTPDelegate, new object[] {
                        OTP}, this.onEndImpresionEtiquetaPorOTPDelegate, this.onImpresionEtiquetaPorOTPCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginImpresionGuiaMasiva(decimal OTP, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImpresionGuiaMasiva(OTP, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia> SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndImpresionGuiaMasiva(System.IAsyncResult result) {
            return base.Channel.EndImpresionGuiaMasiva(result);
        }
        
        private System.IAsyncResult OnBeginImpresionGuiaMasiva(object[] inValues, System.AsyncCallback callback, object asyncState) {
            decimal OTP = ((decimal)(inValues[0]));
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginImpresionGuiaMasiva(OTP, callback, asyncState);
        }
        
        private object[] OnEndImpresionGuiaMasiva(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia> retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndImpresionGuiaMasiva(result);
            return new object[] {
                    retVal};
        }
        
        private void OnImpresionGuiaMasivaCompleted(object state) {
            if ((this.ImpresionGuiaMasivaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImpresionGuiaMasivaCompleted(this, new ImpresionGuiaMasivaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImpresionGuiaMasivaAsync(decimal OTP) {
            this.ImpresionGuiaMasivaAsync(OTP, null);
        }
        
        public void ImpresionGuiaMasivaAsync(decimal OTP, object userState) {
            if ((this.onBeginImpresionGuiaMasivaDelegate == null)) {
                this.onBeginImpresionGuiaMasivaDelegate = new BeginOperationDelegate(this.OnBeginImpresionGuiaMasiva);
            }
            if ((this.onEndImpresionGuiaMasivaDelegate == null)) {
                this.onEndImpresionGuiaMasivaDelegate = new EndOperationDelegate(this.OnEndImpresionGuiaMasiva);
            }
            if ((this.onImpresionGuiaMasivaCompletedDelegate == null)) {
                this.onImpresionGuiaMasivaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImpresionGuiaMasivaCompleted);
            }
            base.InvokeAsync(this.onBeginImpresionGuiaMasivaDelegate, new object[] {
                        OTP}, this.onEndImpresionGuiaMasivaDelegate, this.onImpresionGuiaMasivaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.BeginImpresionCustom(decimal OTP, decimal OTD, int Cantidad, int TipoEtiqueta, decimal Bulto1, decimal Bulto2, decimal Bulto3, decimal Bulto4, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginImpresionCustom(OTP, OTD, Cantidad, TipoEtiqueta, Bulto1, Bulto2, Bulto3, Bulto4, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight.EndImpresionCustom(System.IAsyncResult result) {
            return base.Channel.EndImpresionCustom(result);
        }
        
        private System.IAsyncResult OnBeginImpresionCustom(object[] inValues, System.AsyncCallback callback, object asyncState) {
            decimal OTP = ((decimal)(inValues[0]));
            decimal OTD = ((decimal)(inValues[1]));
            int Cantidad = ((int)(inValues[2]));
            int TipoEtiqueta = ((int)(inValues[3]));
            decimal Bulto1 = ((decimal)(inValues[4]));
            decimal Bulto2 = ((decimal)(inValues[5]));
            decimal Bulto3 = ((decimal)(inValues[6]));
            decimal Bulto4 = ((decimal)(inValues[7]));
            return ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).BeginImpresionCustom(OTP, OTD, Cantidad, TipoEtiqueta, Bulto1, Bulto2, Bulto3, Bulto4, callback, asyncState);
        }
        
        private object[] OnEndImpresionCustom(System.IAsyncResult result) {
            SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado retVal = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight)(this)).EndImpresionCustom(result);
            return new object[] {
                    retVal};
        }
        
        private void OnImpresionCustomCompleted(object state) {
            if ((this.ImpresionCustomCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ImpresionCustomCompleted(this, new ImpresionCustomCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ImpresionCustomAsync(decimal OTP, decimal OTD, int Cantidad, int TipoEtiqueta, decimal Bulto1, decimal Bulto2, decimal Bulto3, decimal Bulto4) {
            this.ImpresionCustomAsync(OTP, OTD, Cantidad, TipoEtiqueta, Bulto1, Bulto2, Bulto3, Bulto4, null);
        }
        
        public void ImpresionCustomAsync(decimal OTP, decimal OTD, int Cantidad, int TipoEtiqueta, decimal Bulto1, decimal Bulto2, decimal Bulto3, decimal Bulto4, object userState) {
            if ((this.onBeginImpresionCustomDelegate == null)) {
                this.onBeginImpresionCustomDelegate = new BeginOperationDelegate(this.OnBeginImpresionCustom);
            }
            if ((this.onEndImpresionCustomDelegate == null)) {
                this.onEndImpresionCustomDelegate = new EndOperationDelegate(this.OnEndImpresionCustom);
            }
            if ((this.onImpresionCustomCompletedDelegate == null)) {
                this.onImpresionCustomCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnImpresionCustomCompleted);
            }
            base.InvokeAsync(this.onBeginImpresionCustomDelegate, new object[] {
                        OTP,
                        OTD,
                        Cantidad,
                        TipoEtiqueta,
                        Bulto1,
                        Bulto2,
                        Bulto3,
                        Bulto4}, this.onEndImpresionCustomDelegate, this.onImpresionCustomCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight CreateChannel() {
            return new ServicioSilverlightClientChannel(this);
        }
        
        private class ServicioSilverlightClientChannel : ChannelBase<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight>, SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight {
            
            public ServicioSilverlightClientChannel(System.ServiceModel.ClientBase<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlight> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public string EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("DoWork", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificarImpresora(string oNombreImpresora, int oRut, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = oNombreImpresora;
                _args[1] = oRut;
                System.IAsyncResult _result = base.BeginInvoke("ModificarImpresora", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndModificarImpresora(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ModificarImpresora", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginImpresionEtiqueta(decimal OTP, decimal OTD, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = OTP;
                _args[1] = OTD;
                System.IAsyncResult _result = base.BeginInvoke("ImpresionEtiqueta", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado EndImpresionEtiqueta(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado _result = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado)(base.EndInvoke("ImpresionEtiqueta", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginImpresionEtiquetaPallet(decimal OTP, decimal OTD, int NPALLET, int BLTOS, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = OTP;
                _args[1] = OTD;
                _args[2] = NPALLET;
                _args[3] = BLTOS;
                System.IAsyncResult _result = base.BeginInvoke("ImpresionEtiquetaPallet", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado EndImpresionEtiquetaPallet(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado _result = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado)(base.EndInvoke("ImpresionEtiquetaPallet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginImpresionEtiquetaPorOTP(decimal OTP, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = OTP;
                System.IAsyncResult _result = base.BeginInvoke("ImpresionEtiquetaPorOTP", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado> EndImpresionEtiquetaPorOTP(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado>)(base.EndInvoke("ImpresionEtiquetaPorOTP", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginImpresionGuiaMasiva(decimal OTP, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = OTP;
                System.IAsyncResult _result = base.BeginInvoke("ImpresionGuiaMasiva", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia> EndImpresionGuiaMasiva(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia> _result = ((System.Collections.ObjectModel.ObservableCollection<SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightclassImpresionGuia>)(base.EndInvoke("ImpresionGuiaMasiva", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginImpresionCustom(decimal OTP, decimal OTD, int Cantidad, int TipoEtiqueta, decimal Bulto1, decimal Bulto2, decimal Bulto3, decimal Bulto4, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = OTP;
                _args[1] = OTD;
                _args[2] = Cantidad;
                _args[3] = TipoEtiqueta;
                _args[4] = Bulto1;
                _args[5] = Bulto2;
                _args[6] = Bulto3;
                _args[7] = Bulto4;
                System.IAsyncResult _result = base.BeginInvoke("ImpresionCustom", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado EndImpresionCustom(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado _result = ((SilverlightApp.ReferenciaServicioWeb.ServicioSilverlightwsEncabezado)(base.EndInvoke("ImpresionCustom", _args, result)));
                return _result;
            }
        }
    }
}
